portworx/kdmp

- cmd/exporter/handler/operator/installmanifests_generated.go
- pkg/drivers/drivers.go
- pkg/drivers/driversinstance/driversinstance.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/options.go
- pkg/executor/kopia/kopia.go
- pkg/executor/kopia/kopiabackup.go
- pkg/executor/kopia/kopiadelete.go
- pkg/kopia/command.go
- pkg/kopia/delete.go
pb-1859: Added changes for kopia snapshot delete functionality.
- Added kopia snapshot delete driver
- Added executor support to invoke kopia snapshot delete
command.
Closes # PB-1859
**Testing:**
1) Vendor the kdmp vendor code to px-backup. 
2) Added the logic to delete the snapshot, if the driver type is kdmp.
3) Created a normal backup object with few PVC.
4) Created a kopia snapshot offline with a repo.
5) Took the snapshot ID and updated the one of the volume of the backup object to have this snapshot ID and driver type as kdmp.
6) Then tried to deleted the backup object from the UI.
7) Made sure the snapshot is deleted after the completion of the backup object …
> pb-1859: Added changes for kopia snapshot delete functionality.

- pkg/apis/kdmp/v1alpha1/dataexport.go
- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/executor/common.go
- pkg/executor/kopia/kopia.go
- pkg/executor/kopia/kopiabackup.go
- pkg/executor/kopia/restore.go
- pkg/executor/restic/resticbackup.go
- pkg/version/version.go
- Storing snapshotID from VolumeBackup CR into DatExport CR
- Creation of secret in source/destination ns for handling multi ns use case
where stork backup/restore/BL CR's are present in kube-system
- Deletion of VolumeBackup CR after a successful backup
PB-1870
Manual Test
Updated DataExport CR
```
[root@prashanth-iron-seer-0 kdmp]# k describe dataexport kopia-aws-mysql-1 -nrst
Name:         kopia-aws-mysql-1
Namespace:    rst
Labels:       <none>
Annotations:  <none>
API Version:  kdmp.portworx.com/v1alpha1
Kind:         DataExport
Metadata:
Creation Timestamp:  2021-09-14T15:05:31Z
Finalizers:
kdmp.portworx.com/finalizer-cleanup
Spec:
Destination:
API Version: …
```
> Changes to DataExport CR for the following

- pkg/drivers/drivers.go
- pkg/drivers/driversinstance/driversinstance.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/executor/kopia/kopia.go
- pkg/executor/kopia/kopiabackup.go
- pkg/executor/kopia/maintenance.go
- pkg/kopia/command.go
- pkg/kopia/maintenancerun.go
- pkg/kopia/maintenanceset.go
```
pb-1876: Added executor and driver for maintenance.
- Added driver interface api for running kopia maintenance set
and run command.
- Also added a executor to call the kopia maintenance set and
run command.
- cronJob will go through all the repos present in the
given backuplocation.
```
Closes #
PB-1876
**Pending items:**
**1) Single PR is becoming bigger, Currently I am not creating the BackupLocationMaintenance CR for status update. I will take it up in separate PR.
2) Also the deletion of CronJobs while deleting the backuplocation.**
**Testing:**
1) Offline created a bucket in minio with generic-backups as directory in it and added two repos using kopia …
> pb-1876: Added executor and driver for maintenance.

- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/options.go
```
pb-1896: added jobname to be part of job option.
- Using jobName provided by caller, if provided for delete and
maintenance job.
- If not provided, taking default value.
```
Closes # PB-1896
>  pb-1896: added jobname to be part of job option.

- pkg/apis/kdmp/v1alpha1/backuplocationmaintenance.go
- pkg/executor/kopia/kopiabackup.go
- pkg/executor/kopia/maintenance.go
- pkg/executor/kopia/restore.go
- pkg/kopia/connect.go
- pkg/kopia/maintenancerun.go
- pkg/kopia/maintenanceset.go
```
pb-1915: added status reason for the repo maintenance, in the case of
failure.
- if one of the repo maintenance fails, Continuing with the other repos in the backuplocation.
- Removed the step to update the volumeBackup CR from
runKopiaRepositoryConnect as it is used by delete and
maintenace command as well.
```
Closes # Pb-1915
**Testing:**
Set the incorrect for the repo connect for testing purpose and maintenance failed in connect and checked that reason is update with error message from kopia command.
```
[root@central-muck-dog-0 ~]# kubectl describe backuplocationmaintenance repo-maintenance-location2-f036c4f -n px-backup
Name: …
```
>   pb-1915: added status reason for the repo maintenance, in the case of failure.

- pkg/controllers/dataexport/reconcile.go
- pkg/executor/common.go
- pkg/executor/kopia/kopiabackup.go
- pkg/kopia/command.go
- pkg/kopia/connect.go
- pkg/kopia/create.go
Adding support for enabling/disabling ssl for kopia connections
PB-1914
None
**Manual test**
Tested using spinning up a local minio without https
1. Have the following CR created with `disablessl: true` 
```
#
apiVersion: stork.libopenstorage.org/v1alpha1
kind: BackupLocation
location:
path: test-bucket
repositoryPassword: k0p1@#GB
s3Config:
accessKeyID: minioadmin
disableSSL: true
endpoint: 70.0.114.169:9000
region: us-east-1
secretAccessKey: minioadmin
type: s3
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"stork.libopenstorage.org/v1alpha1","kind":"BackupLocation","location":{"path":"test-bucket","repositoryP …
```
> PB-1914: Adding supporting for enabling/disabling ssl for kopia connections

- pkg/executor/kopia/kopiabackup.go
- pkg/executor/kopia/kopiadelete.go
- pkg/executor/kopia/maintenance.go
- pkg/executor/kopia/restore.go
pb-1917: made the executor of backup, restore, delete and maintenance executor to run for completion instead of timeout in 2 mints.
Closes # PB-1917
> pb-1917: made the executor of backup, restore, delete and maintenance executor to run for completion instead of timeout in 2 mints.

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/drivers.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/options.go
Add supprot for passing custom certificates
- User creates secret out of public certificate, mounts to controller pod
- Provide certificate path in env SSL_CERT_DIR so job pods can pick and
mount the certificate as part of jobs
PB-1921
Manual test
1. Deployed minio locally with self-signed certificates
2. Mounted the certificate as the secret to stork under kube-system ns
3. Add the following to the stork deployment spec
```
- name: SSL_CERT_DIR
value: "/etc/tls-secrets"
volumeMounts:
- name: tls-secrets
mountPath: "/etc/tls-secrets"
readOnly: true
volumes:
- name: tls-secrets
secret:
secretName: tls-s3-certs
```
4. Trigerred a generic backup/restore on proxy vol which …
> PB-1921: Add support for passing custom certificates

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/utils/utils.go
- pkg/executor/kopia/restore.go
```
pb-1941: Changed the name format for all the kdmp generic backup
resource.
- name format <backup>-<shortUID of backup CR>-<shortID of
PVC>-<NS>
- Added required values like backup object name, uid, pvc name
and id as label in the dataexport, volumebackup, jobs, secret
resource, so that it can be used for filtering, while debugging.
```
Closes # PB-1941
Testing:
1) implemented below naming format for the generic backupResource like DataExport, VolumeBackup, Jobs, secret, roles, roleBindings, ServiceAccount and job pods. 
```
For Backup related resource:
backup-<shortUID of backup CR UID>-<short ID of PVC>-<Namespace>
For restore related resource:
restore-<shortUID of …
```
> pb-1941: Changed the name format for all the kdmp generic backup resource.

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/utils/common.go
Fixing passing correct secret name as per new naming convention to job pods.
PB-1947
Before fixing the failure messages
Pod description when the failure occured
```
Events:
Type     Reason       Age               From     Message
----     ------       ----              ----     -------
Warning  FailedMount  3s (x5 over 10s)  kubelet  MountVolume.SetUp failed for volume "cred-secret" : secret "b-backup-42662d5-84337b7-mysql" not found
[root@prashanth-maple-palm-1 specs]# k describe pod backup-42662d5-84337b7-mysql-9rpj9 -nmysql
Error from server (NotFound): pods "backup-42662d5-84337b7-mysql-9rpj9" not found
```
> PB-1947:  Fixing passing correct secret name to job pod

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/utils/utils.go
-  Do not fail the generic backup if VolumeBackup CR is not found and the job
pod is in waiting state.
Closes #
> PB-1942: Check if the job pods are running if VolumeBackup CR is not found

- pkg/drivers/kopiamaintenance/kopiamaintenance.go
pb-1948: fixed the issue in cron job schedule string.
Closes # pb-1948
With the current string, it was failing with below error.
```
time="2021-10-06T07:24:50Z" level=error msg="StartJob: creation of maintenance job [full-maintenance-repo-dbfa25d] for backuplocation [location1] failed: CronJob.batch \"full-maintenance-repo-dbfa25d\" is invalid: spec.schedule: Invalid value: \"*/* 24 * * *\": Failed to parse int from *: strconv.Atoi: parsing \"*\": invalid syntax"
time="2021-10-06T07:24:50Z" level=warning msg="checkBackupLocationMaintenaceCronjob: failed in creating maintenance secret for backuplocation[location1:dbfa25dd-0767-467a-989c-cc99aef6d8ce]: failed in starting …
```
> pb-1948: fixed the issue in cron job schedule string.

- pkg/drivers/kopiadelete/kopiadelete.go
pb-1961: Delete job ratelimit is broken as delete drivertype was not updated with correct type.
Closes #pb-1961
**Testing:**
Verified that delete job rate limit limits the delete jobs to five count.
> pb-1961: Delete job ratelimit is broken as delete drivertype was not updated with correct type.

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/utils/utils.go
- pkg/jobratelimit/jobratelimit.go
```
pb-1962: added check in backup's StartJob to make sure only one job runs
for a given PVC instance.
- A utils.ErrJobAlreadyRunning error will be return if a backup
job is already running. The caller will retry with this error.
- Renamed jobratelimit.JobCanRun to jobratelimit.CanJobBeScheduled
```
Closes # pb-1962
**Testing:**
Starting four parallel backup on same set of namespace and checked the backups are completed.
Also verified in the log that job schedule failed as already a backup was in progress.
```
time="2021-10-18T02:15:27Z" level=error msg="failed to start a data transfer job, dataexport [backup-f3eb21e-65dff86-ns4]: out of job resources" …
```
> pb-1962: added check in backup's StartJob to make sure only one job runs for a given PVC instance

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/utils/utils.go
```
pb-1988: Using the job secret and creating a temporary backuplocation
for csi cleanup in KDMP controller
- Replaced client.Update to updateStatus which ha ve retry logic
in kdmp controller
- Added AlreadyExists and IsNotFound check while creating and
deleting resources in the kdmp controller
- Returning true from IsJobPending api, when the
containerStatuses is empty.
```
Closes #
PB-1988
**Testing:**
1) Triggered a FA CSI backup with offload to S3 option.
2) Verified that all resources are deleted after backup.
3) Verified the latest CR copies are uploaded to the cloud as well.
> pb-1988: Using the job secret and creating a temporary backuplocation for csi cleanup in KDMP controller

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/options.go
- pkg/drivers/utils/common.go
- pkg/executor/kopia/kopiabackup.go
- pkg/kopia/command.go
- pkg/kopia/compression.go
Added support for compression during backup
- Compression type can be set through kdmp-config map
PB-1984
Manual test
Took a backup of mysql app running
Can be the actual size of 115>B getting reduced to 3.5MB after compression in objectsore
Logs to show compression being set
```
[root@prashanth-winter-fighter-2 kdmp]# k logs -f backup-3fdcd03-5405c0d-mysql-c4sfs -nmysql
+ /kopiaexecutor backup --volume-backup-name backup-3fdcd03-5405c0d-mysql --credentials backup-3fdcd03-5405c0d-mysql --backup-location pk-aws-bl-72bb31e --backup-location-namespace mysql --backup-namespace mysql --repository mysql-mysql-proxy-data --source-path-glob …
```
> PB-1984: Added support for compression during backup

- pkg/controllers/dataexport/reconcile.go
stor-545: updated the missing step to update the volumeSnapshot in updateStatus
Closes # stor:545
> stor-545: updated the missing step to update the volumeSnapshot in updateStatus

- pkg/apis/kdmp/v1alpha1/dataexport.go
- pkg/controllers/dataexport/reconcile.go
> [STOR-551]: pvc creation logic is moved to kdmp reconciler in restore path.

- pkg/drivers/kopiamaintenance/kopiamaintenance.go
In this PR have removed the job framework condition check to unblock the backuplocation creation. 
Closes #
Note: Will work on seperate PR to apply rate limit for maintenance jobs using antinode affinity.
> PB-1986 Backuplocation creation fails in the intergration test.

- pkg/controllers/dataexport/reconcile.go
- pkg/kopia/command.go
```
pb-2009: Add /tmp as default director for the kopia cache and log dir.
- Also added /tmp/kopiaconfig for default config that will be
used. These changes are done as in some platform, we do not
have permission to create dir or file under root dir.
- In the case of retry returning actual error instead of
task.DoRetryWithTimeout function error.
```
Closes # pb-2009
Tested it on the OCS setup.
> pb-2009: Add /tmp as default director for the kopia cache and log dir.

- pkg/controllers/dataexport/reconcile.go
```
pb-2016: Removed the global variable lastKnownStatusOfInProgress and
lastKnownInProgressErrMsg
- For now, adding special handling for cleanup stage alone.
- Remove the check of success or failure in top of the
cleanup handling and then moving to final stage.
- For now, we will directly move to the final stage
in cleanup stage.
- Also, we will not have status transition to initial
and then in-progress. Instead we will maintain
previous stage status itself.
```
Closes # pb-2016
Testing:
With the above fix, ran backup of fa, fb, pxd multi namespace backup. 
It was holding good.
> pb-2016: Removed the global variable lastKnownStatusOfInProgress and lastKnownInProgressErrMsg

- pkg/controllers/dataexport/reconcile.go
Signed-off-by: Diptiranjan
Volume info should show restore object even if it is restored from local snapshots.
Below `2026` restore is the restore from the local snapshot for a FA volume.
> [PB-2026]: Restore size should be shown if restore happens from local snapshot for csi volumes in generic backup.

- pkg/controllers/dataexport/reconcile.go
Treat a snapshot class name provided as "default" or "Default" specifically for CSI snapshot provider.
- If such a snapshot class is detected then assume that it is the CSI snapshotter provider.
Closes #
> Handle default snapshot classes

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/drivers.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/resticbackup/resticbackup.go
- pkg/drivers/resticbackup/resticbackuplive.go
- pkg/drivers/resticrestore/resticrestore.go
- pkg/drivers/rsync/rsync.go
- pkg/drivers/utils/common.go
- pkg/drivers/utils/utils.go
- pkg/executor/kopia/kopiabackup.go
- pkg/kopia/backup.go
```
PB-2042: Fixed backup failure retry due when fatalerror count is encountered
- As part of a reconciler, before the error is reported in stage In-progress, the reconciler will check
if the job has exhausted pod retires amount to backof limit.
- If the pod has restarted this many times, the job will be marked as failed and moved to
cleanup stage.
```
PB-2042
Manual test
1. Simulated error by pointing a wrong backuploation
2. Trigerred a backup
3.  Checked the job pod was restarted till backoff limit is reached and no resources were deleted
4.  After exhausting backoff limit, all resources were deleted and backup marked as failure.
5
> PB-2042: Fixed backup failure retry due when fatalerror count is encountered

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
```
pb-2049: Added pod pending phase check in the buildJob of kopiabackup
- Made checkPVCIgnoringJobMounts to be retried in the case of
failure.
- Will jump to cleanup stage when we hit failure in Transfer
schedule stage
```
Closes # pb-2049
Testing:
Triggered a backup on the namespace which had pending pods and checked that it fails.
> pb-2049: Added pod pending phase check in the buildJob of kopiabackup

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/drivers.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/resticbackup/resticbackup.go
- pkg/drivers/resticrestore/resticrestore.go
- pkg/drivers/rsync/rsync.go
- pkg/drivers/utils/utils.go
- In some cases, once backOff limit is kicked in looks like k8s is not giving was restart count which will be assumed as zero. With this, a backup would be in-progress forever
- Instead of reading the pod restart count, changed the logic to read the job spec and if it has been marked as a failure for whatever reason,  DE CR cleanup would be triggered.
PB-2073
**Manual test**
Case 1
- Trigerred backup of 3 PVC
- Killed one backup pod continuously till backupoff limit is reached
- Eventually, the entire backup is marked as failed.
Case 2:
- Trigerred backup of 3 PVC
- Killed one backup pod only once so that job tries to restart it next time
- Eventually, the entire backup …
> PB-2073 Replacing pod restart count decission with job spec status

- pkg/controllers/dataexport/reconcile.go
pb-2075: Corrected the error handling in checking the PVC bound status.
Closes # pb-2075
Testing:
Tested with the invalid SC and made the PVC to be in pending state.
Backup failed after ~15 to 19 mints.
> pb-2075: Corrected the error handling in checking the PVC bound status.

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/resticbackup/resticbackup.go
- pkg/drivers/resticrestore/resticrestore.go
- pkg/drivers/rsync/rsync.go
- pkg/drivers/utils/utils.go
If the job is running and the node on which the job pod is scheduled gets shut down,
the pod keeps on getting spawned and the corresponding operation (like backup) will be in that stage forever.
With this PR, there is one more additional check in JobStatus has been introduced to check if the node exists or not.
Closes # Pb-2076
Test:
1. The already running job moved to the Failed state (backup - pb-21-system-test-57-ela-2f78453-interval-2021-11-22-131324)
2. Took a new successful backup (backup - pb-21-system-test-57-ela-2f78453-interval-2021-11-23-073026)
3. Again while backup was going on, poweroff one more node (backup - …
> PB-2076: Additional check if node exists in the JobStatus call.

- go.mod
- go.sum
- pkg/controllers/dataexport/dataexport.go
- pkg/utils/crd.go
- pkg/version/version.go
- vendor/github.com/hashicorp/go-version/LICENSE
- vendor/github.com/hashicorp/go-version/README.md
- vendor/github.com/hashicorp/go-version/constraint.go
- vendor/github.com/hashicorp/go-version/go.mod
- vendor/github.com/hashicorp/go-version/version.go
- vendor/github.com/hashicorp/go-version/version_collection.go
- vendor/modules.txt
using crd v1 apis instead of v1beta1 as v1beta1 apis are no more supported in k8s 1.22.
Closes #
PB-1906
backup2 is the backup of a px volume (it's a generic backup - hardcoded the driver to be kdmp) in k8s 1.22.
> [PB-1906]: Support for k8s 1.22 with crd creation using v1 apis.

- pkg/drivers/kopiabackup/kopiabackup.go
pb-2101 Added hostaccess scc in the backup job for ocp platform.
Closes # pb-2101.
Since the SCC issue is blocking the 2.8.1 release, i have hardcoded the SCC for now. Will make it CM configurable.
> pb-2101 Added hostaccess scc in the backup job for ocp platform.

- pkg/controllers/dataexport/dataexport.go
Even after updating dataexport CR, for some of the fields we used to get stale entries.
Hence the change to move to sched ops api.
Closes # PB-2084
Test : Updated in PB-2084
> [PB-2084]: Reading dataexport CR with schedops api instead of contoller client call.

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/options.go
Add support custom backup path in config map
- User can define the custom backup path in kdmp-config cm which will override the standard
/var/lib/kubelet path
PB-2123
NA
> PB-2123: Add support custom backup path in config map

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/utils/utils.go
```
PB-2136 Fetching resource requirements from config map
- Resources like CPU limit, memory limit to be read from config map
```
PB-2136
Manual test
Config map data 
```
[root@prashanth-winter-fighter-2 aws-eks]# kd describe cm kdmp-config -nkube-system
Name:         kdmp-config
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
Data
====
KDMP_KOPIAEXECUTOR_IMAGE:
----
portworx/kopiaexecutor:master
KDMP_KOPIAEXECUTOR_LIMIT_CPU:
----
0.3
KDMP_KOPIAEXECUTOR_LIMIT_MEMORY:
----
1Gi
KDMP_KOPIAEXECUTOR_REQUEST_CPU:
----
0.2
KDMP_KOPIAEXECUTOR_REQUEST_MEMORY:
----
700Mi
KDMP_BACKUP_JOB_LIMIT:
----
5
KDMP_DELETE_JOB_LIMIT:
----
5 …
```
> PB-2136 Fetching resource requirements from config map

- pkg/controllers/dataexport/reconcile.go
```
pb-2131: Fixed couple of error handling issues.
- if snapshotDriveName returned by getSnapshotDriverName is empty, ignore it in cleanupLocalRestoredSnapshotResources
function and move on to kdmp restore stage.
- In other instance, if snapshotDriveName returned by
getSnapshotDriverName is empty, consider it as error.
- The final error cleanupErr return as part of
cleanupLocalRestoredSnapshotResources function is overwritten
and getting nil error, in the case of error. Fixed it.
```
Closes # pb-2131
Testing:
Tested restore on the setup that did not has the volumesnapshot class. It defaulted to S3 object restore.
Note:
1) Currently the reason is getting updated to …
> pb-2131: Fixed couple of error handling issues.

- pkg/controllers/dataexport/dataexport.go
```
pb-2149: Removed the requeue logic from the kdmp controller reconcile
- Removed the requeue logic and now will depend on the update
events and the resynctime intervals for syncing up.
```
Closes # pb-2149
**Testing:**
Tested with backupschedule:
> pb-2149: Removed the requeue logic from the kdmp controller reconcile

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/resticbackup/resticbackup.go
- pkg/drivers/resticrestore/resticrestore.go
cleaning up of dataexport crs should not depend on volumebackup secret.
storage class annotation needs to be kept in staging pvc if source pvc already has it.
cleaning up of binding jobs used for making pvc bound.
clean up of dataexport cr needs to use the precreated secret for backuplocation info
if source pvc has storage class annotation set, use that for staging pvc creation.
Closes # PB-2148
**Test**
Covered following scenarios
Generic Backup and restore of csi volumes with snapshotting with volumebinding mode as WaitForFirstConsumer.
Generic Backup and restore of csi volumes with snapshotting with volumebinding mode as immediate.
Native …
> [PB-2148]: support for cleaning up of binding jobs used for restoring volumes with binding mode as waitforfirstconsumers.

- pkg/apis/kdmp/v1alpha1/dataexport.go
- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/options.go
- pkg/drivers/utils/utils.go
```
pb-2219: Added logic to take care of the custom registry for kopia executor image.
- Added TriggeredFrom and TriggeredFromNs fiels in DE to know from which
module the DE is triggered. Based on that, we will read the regitry name and
image secret from corresponding deployment spec.
- In the each driver, calling utils.GetKopiaExecutorImageRegistryAndSecret to get the
registry name and image secret and use it in the job spec.
```
Closes # pb-2219
1. Testing by integrating with stork.
2. Will raise a separate stork PR.
> pb-2219: Added logic to take care of the custom registry for kopia executor image.

- pkg/drivers/utils/utils.go
```
pb-2219: removed the check for empty image secret as it is valid
```
Closes # pb-2219
> pb-2219: removed the check for empty image secret as it is valid

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/utils/utils.go
```
pb-2196: Added check such that add hostaccess and privileged access only for live backup.
- Also creating the job related resources in the kube-system for the
live backup
- service account
- tls certificate secret
- credential secret
- volumebackup
- job
- job pods
- Fixed the issue of TLS certificate secret getting created in the
incorrect namespace for restore operation.
- Also referring to dataexport.Namespace as a common namespace both the
restore and backup secret creation.
```
Closes # pb-2196
Testing:
1) Deployed a mysql with one PVC with proxy volume.
2) Made replica to zero to test the non live backup.
3) Made replica to zero to test live backup
4) Made …
> pb-2196: Added check such that add hostaccess and privileged access only for live backup.

- pkg/drivers/utils/utils.go
```
pb-2293: add logic to extract registry that contains extra directories in it to use for kopia executor image
```
Closes # pb-2293
United tested with different combination of image format.
> pb-2293: add logic to extract registry that contains extra directories in it to use for kopia executor image

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
```
pb-2323: Fixed issue in the repo name for live generic backup.
- For generic live backup, we will create job and job pods in
the kube-system namespace but repo name, we will still
maintain it as <pvc-ns>-<pvc-name.
- So that restore will able to use the repo name as <pvc-ns>-<pvc-name
```
Closes # pb-2323
Tested with a live backup restore of mysql app.
> pb-2323: Fixed issue in the repo name for live generic backup.

- pkg/executor/kopia/maintenance.go
- pkg/kopia/command.go
- pkg/kopia/maintenanceset.go
Signed-off-by: Diptiranjan
Fixes Quick maintenance jobs if container does not run with root user.
Also fixes if more that one repo is there in the bucket.
Closes # PB-2322
*Test*
1. Tested the quick maintenance job run in OCP  cluster . Results have been updated in PB-2322.
> [PB-2322]: Quick maintenance to use proper username and cleanup older configs before connecting to another repo.

- Dockerfile.kopia
- kopia.repo
The base image is modified from ubuntu to RHEL ubi8-minimal to mitigate security vulnerabilities
Closes #PB-2326
Tested on efs volume (backup and restore) in eks cluster (fixed image : portworx/kopiaexecutor:1.2.0-v2)
> [pb-2326]-(Security) Modify base image to rhel ubi8 minimal from ubuntu

- Dockerfile.unittest
- pkg/drivers/utils/utils.go
```
pb-2330: Made fix to support image name to have custom repo as well.
```
Closes # pb-2330
```
Now we will all the below image format:
<custom-registry-name>/<extra-dir-name>/<custom-repo-name>/image:tag
<custom-registry-name>/<custom-repo-name>/<extra-dir-name>/image:tag
<repo-name>/image:tag -- default registry of docker.io will be taken.
```
> pb-2330: Made fix to support image name to have custom repo as well.

- pkg/drivers/drivers.go
```
pb-2330: remove the portworx repo name from default KopiaExecutorImage to support custom repo
```
Closes # pb-2330
> pb-2330: remove the portworx repo name from default KopiaExecutorImage to support custom repo

- pkg/drivers/utils/common.go
```
pb-2332: Increased the JobPodBackOffLimit from 3 to 10.
- In the case of elastic search, it creates lot of indices files
and it also deletes some of them.
- Kopia some fails with "file not found" error during snapshot
create as it first takes list of files to do the snapshot and
and go one by one. If it could find it, snapshot create fails.
- In these case retry worked. So increased the retry count.
```
Closes # pb-2332
There are other option listed in the ticket. For 2.2.0 px-backup release we are planning to go with retry count increase option. Will try other options in 2.3.0 px-backup.
With 10 retry count, the probability of failure was 2 out 25. 
We try to run …
> pb-2332: Increased the JobPodBackOffLimit from 3 to 10.

- Dockerfile.kopia
**What this PR does / why we need it**: Security fix
Closes #PB-2428
Tested by taking backup and restore on efs volumes (generic backup)
removed `microdnf update` as it was upgrading some packages to vulnerable versions
> [PB-2428] - Security: Remove unused git package to mitigate security vulnerability

- pkg/controllers/dataexport/reconcile.go
- pkg/version/version.go
- Added support for VolumeSnapshot V1 Apis which is GA since kubernetes
1.20 version.
- The v1beta1 is still kept for supporting older K8s versions
**What this PR does / why we need it**: The volumesnapshot API v1beta1 support is removed from k8s version 1.20, hence we need to add v1 APIs along with v1beta1. 
Closes # pb-2328
> pb-2328: Support both v1 & v1beta1 version of the volumeSnapshot

- pkg/version/version.go
The version of volumesnapshot API to be called is decided based on
whichever version of valid VS CRD installed in the system.
This is because for k8s 1.20 both v1 and v1beta can be installed.
**What this PR does / why we need it**: This enables the volumesnapshot version detection based on CRD installed instead of checking the k8s version.
Closes # pb-2820
Unit Test :
Checked by vendoring into stork the KDMP backups are taken gracefully with v1 & v1beta1 version.
Please look into pb-2820 for detailed screenshot for kdmp backup and delete test case operations. And restore operations too.
> pb-2820: Fixed the volumesnapshot version check

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/utils/utils.go
**What this PR does / why we need it**: This PR introduces a config map which is when set to false the resources won'yt be cleaned up. By default resources are cleaned up upon success of failure of backup process. 
Additionally it captures the pod log and redirects that to stork pod log. 
**Which issue(s) this PR fixes** (optional) pb-3031, pb-3003
Closes # pb-3031, pb-3003
Kindly check and let me know  if the place where we are capturing the job-pod log and redirecting would be the apt place or not. Just wandering Will there be a case when capturing at this place will miss the log to be redirected to stork pod. 
** Unit Test **
Tested it by  vendoring this code to stork and taken back-up and simulated a backup failure.
Using the **_backupdiagctl_** …
> Pb 3031 : preventing resource deletion in case of failure using a configMap flag

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/drivers.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/options.go
- pkg/drivers/utils/common.go
- pkg/executor/common.go
- pkg/executor/kopia/kopiabackup.go
- pkg/kopia/backup.go
- pkg/kopia/command.go
- kopia repo create and connect is added with filesystem option
- JOB spec enabled NFS volume mount specific metadata
- Use the PATH variable to represent NFS export directory
- Added NFS related switch cases as per need
Closes #
> PB-2956: Enable volume backup for NFS backed backuplocation

- pkg/apis/kdmp/v1alpha1/resourceexport.go
- pkg/controllers/common.go
- pkg/controllers/resourceexport/reconcile.go
- pkg/controllers/resourceexport/resourceexport.go
- pkg/drivers/drivers.go
- pkg/drivers/driversinstance/driversinstance.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/options.go
- pkg/drivers/utils/common.go
- pkg/executor/nfs/nfsbkpresources.go
```
Job framework for backup to invoke nfs executor
Reconciler changes to act upon ResourceExport CR
```
pb-3093
> PB-3093: Job framework for backup to invoke nfs executor

- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/executor/kopia/maintenance.go
- Added the NFS volume mount specific entries in JOB spec
- identify the kopia repo on the NFS mount path for running the kopia maintenance command.
**What this PR does / why we need it**: Enables the kopia maintenance job to run on NFS based backuplocation
Closes # pb-3091
Still Unit testing the changes
> pb-3091: Enable kopia repo maintenance for NFS BL

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiarestore/kopiarestore.go
- Added nfs mount related configs in job spec
**What this PR does / why we need it**: This enables the  restore of volume from a NFS based backuplocation
Closes # pb-2973
**Special notes for your reviewer**: 
Unit testing is still in progress.
> pb-2973: Support volume restore for NFS based BL

- pkg/executor/nfs/nfsrestoreresources.go
Passing application restore CR correctly with command line param.
Closes # PB-3155
> PB-3155: correctly passing application restore CR for resource restore job.

- pkg/controllers/dataexport/dataexport.go
- pkg/drivers/utils/utils.go
- pkg/executor/common.go
- pkg/executor/nfs/nfsbkpresources.go
- pkg/restic/restore.go
```
pb-3156: Updating the final success status in the backup CR in-memory
copy for uploading it to metadata.json file
```
Closes # pb-3156
Tested and verified the content of the metadata.json file.
> pb-3156: Updating the final success status in the backup CR in-memory for uploading it to metadata.json file

- pkg/executor/nfs/nfsdeleteresources.go
Fixed parameters getting nil values, which lead to delete the parent directory in NFS
Closes # [PB-3164](https://portworx.atlassian.net/browse/PB-3164)
> PB-3164 - Fix delete resource job, to delete the required directory

- pkg/executor/kopia/maintenance.go
When there is a resource only backup the kopia maintenace job goes to crashloopbackoff state and keeps restarting. This is avoided by adding appropriate error check.
**What this PR does / why we need it**: For resource only backup the maintenance job crashloopbackoff contineously due to unavailability of generic-backup dir. Hence added appropriate error check to bail out gracefully.
Closes # pb-3146
Before fix :
After fix:
> pb-3146: For resource only backup maintenance job should pass

- pkg/controllers/dataexport/reconcile.go
- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfsdelete/nfsdelete.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/options.go
- pkg/drivers/utils/utils.go
- pkg/executor/common.go
- pkg/executor/nfs/nfsrestoreresources.go
**What this PR does / why we need it**: This will add support for mountoption passing while taking backup on a NFS Share based backuplocation 
Closes # pb-3159
Yet to add changes to all other places where job is created and some optimisation in PV pvc cleanup path.
> pb-3159 : Added changes for sub-path & mount option for volume backup

- pkg/executor/nfs/nfsbkpresources.go
```
pb-3185: Ported following fix from stork code.
- pr #1150 - pb-3005: Added fix to include the CRDs even if CR is are present.
- pr #1180 - pb-3123: Added logic to trim the group name,
if crds have last three part of groups in common.
```
Closes # pb-3185
> pb-3185: Ported following fix from stork code.

- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/options.go
**What this PR does / why we need it**: The RE CR to pick stork namespace and image-registry location dynamically without hardcoding it.
Closes #
> pb3213 : Adopted TriggeredFrom field from ResourceExport CR

- pkg/controllers/dataexport/reconcile.go
For any older backuplocation which doesn't have any NFS config related setting that need to nullified before accessing its variables.
**What this PR does / why we need it**: For any existing backup location which is of non-nfs type there this nfs config would have been null hence we need to take proper measure to null initialise it before accessing its variables.
Closes # pb-3231
Verified in Kshthij's system it works fine.
> pb-3231: nfsconfig for an old backuplocation need to be nullified

- pkg/drivers/utils/utils.go
```
pb-3232: Add empty storage class to avoid picking default SC for nfs jobs.
```
Closes # pb-3232
Tested on addition of NFS backuploction, with a default SC.
```
[root@siva-bramble-puppy-2 helm]# kubectl  get sc
NAME                 PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
mysql-sc (default)   kubernetes.io/portworx-volume   Delete          Immediate           false                  56m
stork-snapshot-sc    stork-snapshot                  Delete          Immediate           false                  10h
[root@siva-bramble-puppy-2 helm]#
```
> pb-3232: Add empty storage class to avoid picking default SC for nfs jobs

- pkg/drivers/utils/utils.go
**What this PR does / why we need it**:  Added fix for not to fail if there is no docker-registry secret (docregistry-secret)
Closes #[PB-3230](https://portworx.atlassian.net/browse/PB-3230)
Without fix 
After fix
> PB-3230 - Fix for not to fail if image registry secret is not found

- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/utils/utils.go
```
pb-3245: fixed following issues in nfs resource backup and restore path
- jobName, which was used as secret name was not passed
correctly to utils.GetExecutorImageAndSecret api.
- Namespace to CreateImageRegistrySecret api need to passed
based on the executor type.
```
Closes # pb-3245
Tested on QA cluster.
> pb-3245: fixed following issues in nfs resource backup and restore path

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiadelete/kopiadelete.go
```
pb-3249: Added change to trim the label value, if it is greater than 63 chars
```
Closes # pb-3249
Tested deletion of backup object greater than 63 char.
> pb-3249: Added change to trim the label value, if it is greater than 63 chars

- pkg/drivers/utils/common.go
- pkg/executor/common.go
- pkg/executor/nfs/nfsbkpresources.go
```
pb-3216: Taking QPS and burst value from the kdmp-config for nfs executors
```
Closes # pb-3216
> pb-3216: Taking QPS and burst value from the kdmp-config for nfs executors

- cmd/executor/nfs/nfs.go
- pkg/executor/nfs/nfsbkpresources.go
```
pb-3284: Adding git version to nfs executor, travis change to push nfs
executor image
```
pb-3284
Log showing kdmp git version
```
[root@prashanth-indigo-bear-1 prashanth]# k logs -f -nkube-system nfs-backup-71fe4ce-only-resources-6q47c
+ /nfsexecutor backup --app-cr-name only-resources-4-5aa8237 --backup-namespace only-resources --rb-cr-name nfs-backup-71fe4ce-only-resources --rb-cr-namespace kube-system
^[[A
time="2022-11-14T06:49:25Z" level=info msg="Creating default CSI SnapshotClasses"
W1114 06:49:25.836833       1 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver …
```
> pb-3284: Adding git version to nfs executor, travis change to push nfs

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/executor/common.go
- pkg/executor/nfs/nfsrestoreresources.go
- pkg/executor/nfs/nfsrestorevolcreate.go
`Added support for creating namespace if not present during vol restore`
pb-3278
ResourceExport CR created in kube-system ns
ResourceBackup CR created in kube-system ns
PVC creation happens in individual ns
Backup screen shot of two NS 
Restore of the above (to two ns)
Restoring to one namesapce, backup taken for two ns
Restoring with retain option for existing ns
> pb-3278 Added support for creating namespare if not present during vol restore

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
```
pb-3317: Avoiding the pod count for the pvc usage for live backup
calculation, if it is used by kdmp job pods.
```
Closes # pb-3317
Tested with four parallel backup o
n same namespace.
> pb-3317: Avoiding the pod count for the pvc usage for live backup calculation, if it is used by kdmp job pods.

- pkg/executor/kopia/maintenance.go
```
pb-3318: using kopia.repository.f for NFS BL, to determine whether it is a kopia repo dir
```
Closes # pb-3318
Tested with and with out fix:
With out fix:
```
[root@kumar-2 helm]# kubectl  logs -f quick-maintenance-repo-5a7549e-27816076-z7wll -n central
+ /kopiaexecutor maintenance --cred-secret-name maintenance-repo-5a7549e --cred-secret-namespace central --maintenance-status-name maintenance-repo-5a7549e --maintenance-status-namespace central --maintenance-type quick
time="2022-11-20T17:16:02Z" level=info msg="type: nfs"
[root@kumar-2 helm]#
```
With fix:
```
[root@kumar-2 helm]# kubectl  logs -f quick-maintenance-repo-5a7549e-27816099-q2qsb -n central
+ …
```
> pb-3318: using kopia.repository.f for NFS BL, to determine whether it  is a kopia dir

- pkg/drivers/drivers.go
- pkg/executor/kopia/maintenance.go
- pkg/executor/nfs/nfsbkpresources.go
- pkg/executor/nfs/nfsrestorevolcreate.go
```
pb-3335: Moving NFS mount to /mnt from /tmp
- When both quick and full maintenance run together, it causes contention due to which both
the maintenace jobs error out which leads to cleaning up of cache directory
- Cache directory was set to /tmp where we also mounted NFS PVC leading to loosing of
NFS backed up data
```
pb-3335
> pb-3335: Moving NFS mount to /mnt from /tmp

- pkg/drivers/kopiamaintenance/kopiamaintenance.go
The quick and full maintenance job schedule need to be altered so that they won't try to run at the same time.
Closes #
> pb-3334: Alter the maintence job schedule

- pkg/drivers/utils/common.go
- pkg/executor/nfs/nfsbkpresources.go
```
pb-3298: Added check not to check for service account secret token from 1.24.0 k8s onwards
```
Closes #pb-3298
Tested by vendor to the stork and kdmp backup.
> pb-3298: Added check not to check for service account secret token from 1.24.0 k8s onwards.

- pkg/version/version.go
Altered the gitVersion to point to 1.2.4 in kdmp 1.2.4 branch
Closes #
> Altered the version of kdmp from 1.2.2 to 1.2.4

- pkg/drivers/kopiabackup/kopiabackuplive.go
```
pb-3494: Added check to include mount for the CSI migrated volumes.
- Check if the pv spec contains pv.kubernetes.io/migrated-to annotation,
then add the mount to the volume dir as it was provisioned by the CSI provisioner.
```
Closes #pb-3494
Testing: Verified on the Sanjay's setup and restore was successful.
> pb-3494: Added check to include mount for the CSI migrated volumes.

- go.mod
- go.sum
- pkg/executor/nfs/nfsbkpresources.go
- vendor/github.com/libopenstorage/stork/drivers/volume/csi/csi.go
- vendor/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationclone.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationregistration.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go
- vendor/github.com/libopenstorage/stork/pkg/resourcecollector/resourcecollector.go
- vendor/github.com/libopenstorage/stork/pkg/utils/utils.go
- vendor/modules.txt
```
pb-3447: Added uploadCSISnapshots to upload the snapshot.json as part of nfs executor job.
```
Closes #pb-3447
Testing:
snapshot.json from minio backuplocation:
```
{"volumeSnapshots":{"backup-aaa715bf6405-9f7465534d49":{"metadata":{"name":"backup-aaa715bf6405-9f7465534d49","namespace":"mysql-pso","uid":"4a7e8cee-7e30-4e3e-8c93-6bb5e130b84e","resourceVersion":"401015","generation":1,"creationTimestamp":"2023-01-29T07:14:41Z","finalizers":["snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection"],"managedFields":[{"manager":"stork","operation":"Update","apiVersion":"snapshot.storage.k8s.io/v1","time":"2023-01-29T07:14:41Z","fieldsType":"FieldsV1","fieldsV1 …
```
> pb-3447: Added uploadCSISnapshots to upload the snapshot.json as part of nfs executor job.

- pkg/executor/kopia/kopiabackup.go
- pkg/kopia/command.go
- pkg/kopia/connect.go
- pkg/kopia/create.go
```
pb-3637: Added S3 region option to the kopia command
```
Closes #pb-3637
Tested with the Oracle S3 objectstore with different region value.
> pb-3637: Added S3 region option to the kopia command

- pkg/controllers/dataexport/reconcile.go
```
pb-3633: Added v1/v1beta version check in calling volumesnapshot class get in getSnapshotDriverName()
```
Closes # pb-3633
Tested on the QA setup, Now we are not seeing the deprecated message.
> pb-3633: Added v1/v1beta version check in calling volumesnapshot class get in getSnapshotDriverName()

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
```
pb-3683: Added correct configmap name for reading admin namespace.
```
Closes # pb-3683
Testing the kdmp path.
> pb-3683: Added correct configmap name for reading admin namespace.

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/drivers.go
- pkg/drivers/driversinstance/driversinstance.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/executor/nfs/nfs.go
- pkg/executor/nfs/nfsbkpresources.go
- pkg/executor/nfs/nfscsirestore.go
Reconciler changes with csi local snapshot restore job.
Separate executor for restoring csi local snapshots from generic backups.
Closes # PB-3576
> PB-3576: Reconciler and CSI local restore job changes for supporting NFS backuplocation with generic backups

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiabackup/kopiabackuplive.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/drivers/nfsdelete/nfsdelete.go
- pkg/drivers/nfsrestore/nfsrestore.go
```
pb-3855: Adding the imageregistry secret to kdmp jobs, only if it is present in the source deployment spec ( stork or px-backup).
```
Closes # pb-3855
Testing:
Planning to ask QA to test the kdmp backup and restore with imageregistry secret setup.
> pb-3855: Adding the imageregistry secret to kdmp jobs, only if it is present in the source deployment spec ( stork or px-backup).

- Makefile
- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
fixes the issue related to nfscsirestore taking wrong export and sub path. Also patched the name for nfscsirestore job
Closes #
> PB-3854: Patch job name and nfs export path 

- pkg/executor/common.go
- pkg/executor/nfs/nfsrestorevolcreate.go
```
pb-3891: fixed issues in restore pvcs from multiple driver from backup.
- fixed the issue in returning error from nfsrestorevolcreate job
- corrected the volume list passed to skipVolumesFromRestoreList
- Fixed the issue in retry logic of UpdateStatusInResourceBackup
```
Closes # pb-3891
Tested on QA setup:
> pb-3891: fixed issues in restore pvcs from multiple driver from backup.

- pkg/executor/nfs/nfsbkpresources.go
```
pb-3892: Do not collect the storageclass.json, if it is not csi driver
```
Closes # pb-3892
Tested that the storageclass.json was not getting create for non-csi case ( protworx)
> pb-3892: Do not collect the storageclass.json, if it is not csi driver

- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/drivers.go
- pkg/executor/nfs/nfsbkpresources.go
- In case of large resource count we need to limit the number of resource passed for GetResource() call
- This prevents overwhelming of k8s api server
**What this PR does / why we need it**: This PR is meant of cluster having large resource and it prevents  congestion at k8s PAI server by rate limiting the number of resource that is queried  to K8s server. 
Closes # pb-3883
> pb-3883: Added resource-count-limit configmap for GetResource call

- go.mod
- go.sum
- pkg/executor/nfs/nfsrestoreresources.go
- pkg/executor/nfs/nfsrestorevolcreate.go
- vendor/github.com/libopenstorage/stork/drivers/volume/aws/aws.go
- vendor/github.com/libopenstorage/stork/drivers/volume/azure/azure.go
- vendor/github.com/libopenstorage/stork/drivers/volume/csi/csi.go
- vendor/github.com/libopenstorage/stork/drivers/volume/gcp/gcp.go
- vendor/github.com/libopenstorage/stork/drivers/volume/kdmp/kdmp.go
- vendor/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go
- vendor/github.com/libopenstorage/stork/drivers/volume/volume.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackupschedule.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationclone.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go
- vendor/github.com/libopenstorage/stork/pkg/cmdexecutor/cmdexecutor.go
- vendor/github.com/libopenstorage/stork/pkg/k8sutils/k8sutils.go
- vendor/github.com/libopenstorage/stork/pkg/log/log.go
- vendor/github.com/libopenstorage/stork/pkg/resourcecollector/persistentvolume.go
- vendor/github.com/libopenstorage/stork/pkg/resourcecollector/resourcecollector.go
- vendor/github.com/libopenstorage/stork/pkg/rule/rule.go
- vendor/github.com/libopenstorage/stork/pkg/schedule/schedule.go
- vendor/github.com/libopenstorage/stork/pkg/snapshot/controllers/snapshotrestore.go
- vendor/github.com/libopenstorage/stork/pkg/snapshot/controllers/snapshotschedule.go
- vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter_csi.go
- vendor/modules.txt
```
pb-3907: passing backuplocation CR details to resourceCollector.PrepareResourceForApply
- Need to call the getAzureSession in UpdateMigratedPersistentVolumeSpec api, which is called in
preparePVResourceForApply of resourcecollector api.
- So passing the backuplocation CR details to get the cluster
creds from the backuplocation CR and get the azure session details.
```
Closes # pb-3907
Tested on the QA setup. Restore completes.
> pb-3907: passing backuplocation CR details to resourceCollector.PrepareResourceForApply

- pkg/executor/nfs/nfsbkpresources.go
**What this PR does / why we need it**: This PR is to have CSI snapshot contents uploaded before resource and namespaces. Thus avoiding the change of missed CSI snapshot content uploads when there is an issue in resource or namespace upload. 
Closes # https://portworx.atlassian.net/browse/PB-3911
> PB-3911: modifying the order of uploading contents to BL

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiarestore/kopiarestore.go
```
pb-3913: Added failed mount event check in the jobstatus and return error to make the job fail.
```
Closes # pb-3913
**Note: Deletion will be taken care by pb-3915
Testing:**
Tested the backupschedule with unreachable NFS server.
> pb-3913: Added failed mount event check in the jobstatus and return error to make the job fail.

- pkg/drivers/kopiadelete/kopiadelete.go
pb-3915: Added failed mount event check in the job status and return error to make the job fail. In case of kopia delete.
Closes #PB-3915
Unit test is in progress.
Currently blocked due to repo access issue
>  PB-3915: Add IsJobPodMountFailed check in kopiadelete JobStatus

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/kopiarestore/kopiarestore.go
```
pb-3916: Made the step to update the restore status for both nfs and non nfs case in stageLocalSnapshotRestoreInProgress api
```
Closes # pb-3916
Testing:
Tested both the nfs and S3 backuplocation with KDMP Localsnapshot restore. Now size show properly.
> pb-3916: Made the step to update the restore status for both nfs and non nfs case in stageLocalSnapshotRestoreInProgress api

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiarestore/kopiarestore.go
MountFailed related error need to be generic to be applicable for both S3 and NFS backuplocation scenario.
Closes #pb-3929
> pb-3929: modify the error msg to be generic for kopia

- go.mod
- go.sum
- pkg/executor/nfs/nfsbkpresources.go
- vendor/github.com/libopenstorage/stork/drivers/volume/csi/csi.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go
- vendor/github.com/libopenstorage/stork/pkg/snapshot/controllers/snapshotschedule.go
- vendor/modules.txt
```
PB-3936: Fixed the issue in taking crds backup with nfs backuplocation.
- Also fixed the way the resource is fetched in the nfs resource
job pod.
```
Closes # pb-3936
```
Tested below cases:
1) Validated backup and restore of the elastic search deployment deployed by the operatore.
2) backup of multi namespace with resourceType - with one namespace ns1 having resourceType and another one namespace ns2 with out ns.
- In this case, the resourceType's resource of the ns1 was backedup. No resources from ns2 was backed up.
3) backup of multi namespace with includeresource and all resource - with includeResource one namespace ns1 and all resources with another namespace …
```
> PB-3936: Fixed the issue in taking crds backup with nfs backuplocation.

- pkg/controllers/dataexport/reconcile.go
- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/drivers/utils/common.go
- pkg/executor/nfs/nfscsirestore.go
- Cleaned up the below resources after successful completion of restore
- serviceAccount
- clusterRole & clusterRoleBinding
- cred-secret
- Removed an unwanted cred-secret creation logic
- Added deletion logic to clear CRB and clusterRole in utility function
**What this PR does / why we need it**: It cleans up some unwanted resources after a successful restore operation
Closes #
> pb-3927: cleanup unwanted resources after a successful restore operation

- pkg/controllers/dataexport/reconcile.go
```
pb-3928: Fixed ivalid access of the volumesnapshot from the pvc spec with localsnapshot restore cleanup
```
Closes # pb-3928
Tested parallel restore on the QA IBM setup.
> pb-3928: Fixed ivalid access of the volumesnapshot from the pvc spec with localsnapshot restore cleanup

- Dockerfile.kopia
- Dockerfile.nfs
**What this PR does / why we need it**:  fixing high security CVEs
Upgraded to ubi9 as a base image and removed curl package as it comes as a part of the base image
Closes # 
kopiaexecutor : [PB-4074](https://portworx.atlassian.net/browse/PB-4074)
nfsexecutor : [PB-4075](https://portworx.atlassian.net/browse/PB-4075)
[PB-4074]: https://portworx.atlassian.net/browse/PB-4074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PB-4075]: https://portworx.atlassian.net/browse/PB-4075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PB-4074, PB-4075 : fixing high security CVEs

- .github/workflows/security-ci.yml
**What this PR does / why we need it**: GitHub Action Workflow for OSS Scanning
Closes #
> GitHub Action Workflow for OSS Scanning

- .travis.yml
- pkg/controllers/resourceexport/reconcile.go
```
pb-4072: Added alreadyExists error for the resourceBackup CR creation.
- Sometime, if the stork restart the reconcile enters again with
kdmpapi.ResourceExportStageInitial stage and tries to create the
resourceBackup again and it fails if it already exists.
```
Closes # pb-4072
Testing:
The bug was found in one of the system testing that trying to restart the stork pod, when backup/restore was in-progress.
With the fix, verified that system test run passes.
> pb-4072: Added alreadyExists error for the resourceBackup CR creation.

- pkg/executor/common.go
- pkg/executor/kopia/kopiadelete.go
- pkg/kopia/command.go
- pkg/kopia/list.go
**What this PR does / why we need it**: This PR add the functional to perform snapshot list before deleting any snapshots and carries out the below
1. When the snapshot to be deleted is not found in the kopia repository(i.e snapshot list), delete job does not proceed on `kopia delete` 
2. When the snapshot to be deleted is found in the snapshot list , delete job will proceed on `kopia delete`
Closes #[PB-4110]( https://portworx.atlassian.net/browse/PB-4110)
Scenario 1 - When kopia snapshot is already deleted before before triggering backup object delete
Scenario 2 - Normal flow of kdmp+localsnapshot delete
[PB-4110]: https://portworx.atlassian.net/browse/PB-4110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> PB-4110 - Handle snapshot delete when s3 objects are removed or when snapshot already deleted

- pkg/controllers/dataexport/reconcile.go
```
pb-4237: Resetting the dataexport's SnapshotStorageClass value to empty
- If the local snapshot restore fails, we decide to try the
kopia restore. In that we will reset the dataexport's
SnapshotStorageClass value to empty, so that during cleanup, we will not
check for any local snapshot resource cleanup.
- The localsnapshot restore resources will be cleanup, before
starting the kopia restore.
```
Closes # pb-4237
Testing:
1) The issue was easily reproduced by restoring KDMP Localsnapshot backup on a cluster that does not have volumesnapshotclass.
2) In this case, the localsnapshot restore will fail and we will try Kopia restore.
3) With out fix, the kopia restore …
> pb-4237: Resetting the dataexport's SnapshotStorageClass value to empty

- Dockerfile.kopia
- kopia.repo
**What this PR does / why we need it**: This PR fixes kopia installation by downloading the setup from github assets rather than from kopia rhel repository 
Closes # https://portworx.atlassian.net/browse/PB-4446
> PB-4446 - Added changes to install kopia from github assets

- pkg/controllers/dataexport/reconcile.go
Capture job's and pod's describe output in case of failure.
Closes #309 https://portworx.atlassian.net/browse/PB-4396
- Added ENABLE_PX_GENERIC_BACKUP: "true" - key-value pair to the data section in kdmp-config file to trigger generic backup with px-vol cluster
- 
- Simulated a pod failure by giving wrong command to run inside the container which exits with non-zero status code
- Checked the log for the leader stork pod while triggering a live backup
> PB-4396 Added code to capture pod's description incase of failure

- pkg/executor/kopia/kopiabackup.go
```
pb-4579: Passing --sseType to kopia only when S3Config.SseType is passed.
```
Closes # pb-4579
Added minor fix in the kopia source, to make sse-type as optional.
Before Fix:
```
cmd.Flag("sseType", "SSE types, only SSE-S3 is supported.").Required().StringVar(&c.s3options.SseType)
```
After Fix:
```
cmd.Flag("sseType", "SSE types, only SSE-S3 is supported.").Default("").StringVar(&c.s3options.SseType)
```
Will add the test result in the Px-backup PR and will add a reference to it.
https://github.com/portworx/px-backup/pull/1352 - px-backup PR
> pb-4579: Passing --sseType to kopia only when S3Config.SseType is passed

- pkg/executor/common.go
```
pb-4579: Added check to ignore sseTypePath secret file as it is optional.
```
Closes #pb-4579
**Testing:**
On the QA cluster valid the deletion and maintenance job works for the backuplocaiton which did not had SseType field.
> pb-4579: Added check to ignore sseTypePath secret file as it is optional

- pkg/controllers/dataexport/reconcile.go
**What this PR does / why we need it**:  To error out proper message when storage class is not present in restore cluster in case of kdmp
Closes #
> PB-4606: Check for Storage Class Present in Restore Cluster

- .travis.yml
- Makefile
- go.mod
**What this PR does / why we need it**: [Security] - upgrade golang to 1.21.2 for mitigating security risks
Closes #
> [Security] - upgrade golang to 1.21.2 for mitigating security risks

- pkg/controllers/dataexport/reconcile.go
```
pb-4969: Fixed issue with backuplocation CR variable, which was causing
the nfs backup issue.
- backuplocation CR variable scope was lost inside the if
condtion. Because of this the nfs parameters are not passed to kopia job.
- The kopia writes the snapshot file directly  inside the job
pod file system and files are lost once the pod is completed.
- Since the nfs parameters are not passed, the nfs pvc was not
getting mounted inside the nfs job pod.
```
Closes # pb-4969
Testing:
1) Tested both the backup and restore with NFS backuplocation.
> pb-4969: Fixed issue with backuplocation CR variable, which was causing the nfs backup issue.

- pkg/controllers/dataexport/reconcile.go
```
pb-4943: Added fix to return proper error message, if the kdmp backup
fails in DataExportStageTransferInProgress stage.
- Currently, we are passing empty reason for the failed case, so
the reason is not passed to the UI. In the failed case, it shows empty reason.
```
Closes # pb-4943
Testing:
1) Created a kdmp backup, when the job is created, Deleted the job pod. 
**Before Fix:**
**After Fix:**
> pb-4943: Added fix to return proper error message, if the kdmp backup fails in DataExportStageTransferInProgress stage.

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/options.go
- pkg/drivers/utils/utils.go
- pkg/executor/kopia/kopia.go
- pkg/executor/kopia/kopiabackup.go
- pkg/executor/kopia/kopiadelete.go
- pkg/executor/kopia/maintenance.go
- pkg/executor/kopia/restore.go
This PR introduces changes to include the debug level of logs for all kopia related operations. Needed, so it can be easier to debug any messages in the future when required.
Closes #
Attaching screenshots for reference
> Pb-4844: Made changes in kdmp for it to enable debug level log messages

- pkg/drivers/drivers.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/drivers/nfsdelete/nfsdelete.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/utils/utils.go
```
pb-5288: Adding "sidecar.istio.io/inject: false" label to the job pods.
- Currently, with Istio enabled on a namespace, it will create
istio-proxy container for all the pods. With the job pod, there is a
known issue where even though the actual job pod container completes,
the istio-proxy continues to runs.  This makes the job pod to hang.
- This issue is fixed with k8s 1.28.0 and Istion 1.19.0. Still that point,
we are providing a option to customer such they can set the
KDMP_DISABLE_ISTIO_CONFIG to true in the kdmp-confg configmap and we
will add the "sidecar.istio.io/inject: false" labels to the job pod that
we create. That way the istio-proxy container will not be added to the job
pod, even if the Istio is enabled at the namespace.
``` …
> pb-5288: Adding "sidecar.istio.io/injec: false" label to the job pods.

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/drivers/nfsdelete/nfsdelete.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/utils/utils.go
```
pb-5288: Added changes to read the istio disable config from px-backup-config for delete and maintenance apis.
```
Closes #pb-5288
Will add the test result with px-backup PR.
> pb-5288: Added changes to read the istio disable config from px-backup-config for delete and maintenance apis.

- pkg/controllers/dataexport/reconcile.go
```
pb-5450: Added change to wait for the deletion of application pvc before switching to kdmp restore, when the csi restore failed.
Root cause:
If local csi restore fails, we will delete the PVC created to restore from local csi snapshot.
Will wait for the deletion of the PVC to complete by calling get PVC.
Otherwise, the PVC creation in the kdmp snapshot restore, does not creates the new PVC as we will use same name.
```
Closes # pb-5450
1) Tested on the ocp cluster. 
2) On source OCP cluster took KDMP/CSI backup.
3) On different dest OCP cluster try to restore, CSI restore failed as snapshot are not available ( exepected behaviour).
4) Then it will automatically …
> pb-5450: Added change to wait for the deletion of application pvc before switching to kdmp restore, when the csi restore failed.

- .travis.yml
- Makefile
- pkg/version/version.go
**What this PR does / why we need it**: Updating travis to have master branch related changes.
Closes #
> Updated travis to reflect master branch changes

- pkg/controllers/dataexport/reconcile.go
- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiadelete/kopiadelete.go
- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/drivers/nfsdelete/nfsdelete.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/utils/utils.go
1.Added utility function to display the job pod log,events and description.
Added the call to the jobStatus function where we check the status of job to print logs in case of failure.
2.Code cleanup: Removed unnecessary *err!=nil* blocks and removed appendPodLogtoStork function 
3.Fix label for NFSCSIrestore job which was pointing to NFSRestore before
Closes #PB-4572
Screenshots of 
1.kopiabackup driver mountfailed and job failed:
2.nfsbackup mount and job failed:
kopiarestore mount fail:
nfsrestore mount and job fail:
NFSCSIrestore:
Delete and maintenace related screenshot will be added in the PR for px-backup
> PB-4572:Added logging of pod describe,events and Jobpod log in job failure scenarios 

- pkg/controllers/dataexport/reconcile.go
```
pb-5438: Resetting the pvc.Spec.Selector in the kdmp and csi as it is dynamic provisioning.
```
Closes # pb-5438
**Note:**
```
One PR will raised in stork code to take care of CSI in the RestoreFromLocalSnapshot function of /pkg/snapshotter/snapshotter_csi.go file.
```
**Testing:**
1) Created a static NFS pv and linked it with the PVC with a label selector:
```
➜  ~ kubectl get pvc -n nfs-test -o yaml
apiVersion: v1
items:
- apiVersion: v1
kind: PersistentVolumeClaim
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"nfs-pvc","namespace":"nfs-test"},"spec":{ …
```
> pb-5438: Resetting the pvc.Spec.Selector in the kdmp and csi as it is dynamic provisioning.

- pkg/controllers/dataexport/reconcile.go
- pkg/controllers/resourceexport/reconcile.go
RCA
After taking a nfs volume backup and resource backup we were not cleaning up the image-secret-jobname
causing increase in the resource count in the next backups.
Solution implemented
dataExportCR reconciler cleanup should be updated to delete the secret even if the transferID is present
resourceExportCR reconciler cleanup should be updated to delete the secret if the transferID is present.
To clean the image secret resource during cleanup of data export and resource export resources
Closes #PB-5815
> PB-5815: clean image secrets during data export and resource export cleanup.

- pkg/executor/kopia/maintenance.go
**What this PR does / why we need it**: It adds logs to identify if it's a resource only backup in case of s3 bl
Closes # [PB-5823](https://portworx.atlassian.net/browse/PB-5823)
**RCA**-
If we take resource only backup (without any pvc), then we don't create a generic backup dir on the backup location
**TestMaintenanceJobForResourceOnlyBackup** checks for the log in the maintenance pod log to verify if it's a resource only backup
If we don't find any generic backup dir, then we throw this warning "No directory exists, verify if it is a resource only backup"
This log statement is covered in nfs backup flow but not in s3 bl scenario
**ss of quick maintenance pod log**
[PB-5823]: …
> added log to identify if it's a resource only backup

- pkg/drivers/kopiamaintenance/kopiamaintenance.go
`Avoid running maintenance jobs in parallel`
pb-5826
With changes
Cronjob showing the modified policy - Quick maintenance
```root@ip-10-13-199-5:~/prashanth# k describe cronjob quick-maintenance-repo-ba82f84 -ncentral
Name:                          quick-maintenance-repo-ba82f84
Namespace:                     central
Labels:                        kdmp.portworx.com/backuplocation-object-name=old-minio-bl
kdmp.portworx.com/backuplocation-object-uid=ba82f84f-4bc8-4ae7-9269-c2708b7d7b4c
kdmp.portworx.com/driver-name=kopiamaintenance
Annotations:                   stork.libopenstorage.org/skip-resource: true
Schedule:                      */1 * * * *
Concurrency Policy: …
```
> pb-5826: Not running parallel maintenance jobs

- pkg/controllers/dataexport/reconcile.go
- pkg/drivers/options.go
- pkg/drivers/rsync/rsync.go
- pkg/drivers/rsync/rsync_test.go
- pkg/drivers/utils/utils.go
**Unit test result**:
```
➜  go test -v -tags unittest -coverprofile=profile.out -covermode=atomic  github.com/portworx/kdmp/pkg/drivers/rsync
=== RUN   TestToJobName
--- PASS: TestToJobName (0.00s)
PASS
coverage: 8.3% of statements
ok      github.com/portworx/kdmp/pkg/drivers/rsync      1.776s  coverage: 8.3% of statements
```
The fix is for making rsync job name within job name limit.
Also added dataexport UID to create new job everytime if dataexport spec gets reapplied with same name.
Closes # PWX_36486
Test results have been updated in PWX-36486
> PWX-36486: Rsync job name to be restricted within max length limit.

- pkg/controllers/dataexport/reconcile.go
- KDMP backup fails if the pvc names is more than 63 chars, as we use the pvc name as labels in data export CR.
- So, fixed the labels validation for dataexport CR for pvc name
Closes #
> PB-6351: handling labels validation for dataexport CR for pvc name

- pkg/executor/nfs/nfsbkpresources.go
- pkg/executor/nfs/nfsrestorevolcreate.go
This PR introduces two changes where when the objects are uploaded to NFS location. Now, we check if any of the PV and PVCs have failed and skip those while uploading the `resources.json` file. 
During restore from NFS in case if it is partial backup, we skip the PVCs which were either in `Failed` or `Skipped` state
Closes #
Restore is successful when the backup was in partial backup state
PVC which was in failed state during backup is skipped during restore and the restore status is as successful:
Logs of nfs executor during restore:
As seen below, in the resources.json file, the PVC which was in failed state is not uploaded in the file in the BL
> PB-6205: Support for NFS related partial backup and restore of those partial backups

- go.mod
- go.sum
- pkg/executor/nfs/nfsbkpresources.go
- pkg/executor/nfs/nfsrestorevolcreate.go
- vendor/github.com/libopenstorage/stork/drivers/volume/csi/csi.go
- vendor/github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1/applicationbackup.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go
- vendor/modules.txt
We have decided to remove status skipped in volInfos for the volumes which are skipped and rather have status as failed itself for the skipped volumes. So, this PR implements that particular feature
Closes #
Scenario1 : NFS location is in Limited Availability and multi NFS backup is taken - Partial Backup
https://github.com/libopenstorage/stork/assets/148333439/3604eba5-b1fd-429a-84a5-06476c904229
Scenario2: NFS location in limited Availability and only KDMP backups are taken, which are skipped and the backup is in failed state
Scenario 3: Valid NFS location and multi NS backup with KDMP and non-KDMP vols - successful backup
Scenario 4: Valid NFS location and only KDMP …
> PB-6609: PVCs which are skipped are marked as fail in volInfos

- pkg/drivers/kopiamaintenance/kopiamaintenance.go
- pkg/drivers/options.go
Add S3DisableSSL field to the JobOptions to fix tls secret mount to the maintenance job spec.
tls secret is appended to the maintenance job spec based on the s3Disable Value
**What this PR does / why we need it:**
To fix maintenance job fix issue
**Which issue(s) this PR fixes**
PB-6631
**Steps to reproduce the issue:**
1. Deploy the Px-backup with SSL_CERT_DIR using --set caCertsSecretName=px-s3-certs while install/upgrade through helm
2. Create the multiple backup locations objects with disable and enable ssl.
3. Restarting the px-backup pod
3. The maintenance jobs were triggered for the disable ssl failed with an event **Mount Failed**
**Special notes for your reviewer:**
Below are the screen shots after the fix applied now we can see the maintenance job spec is not having the …
> PB-6631: [AMEX] Fix maintenance job stuck in pending state

- pkg/executor/kopia/kopiadelete.go
**What this PR does / why we need it**: Fixed repository file path for deletion 
Closes # https://purestorage.atlassian.net/browse/PB-6880
> PB-6880: Fixed repository file path for deletion 

- .gitignore
- pkg/executor/nfs/nfsrestorevolcreate.go
This PR gets secret env from stork deploy used in nfs restore of secured portworx volumes. The access key retrieved is passed as env variable in nfs restore job to complete nfs restore
Closes #PB-6687
**Test Cases combination performed**:
Backup and restore
1. Portworx (Across Cluster)
2. Portworx + CSI + OFFLOAD ( Across Cluster )
3. Portworx + KDMP ( Across Cluster )
4. Portworx + CSI ( Same Cluster ) ( Retain ) ( Deleted App before Restore )
5. BACKUP_TYPE = Generic
> PB-6687 :: Placing PX secret in nfsrestore job spec 

- .gitignore
- pkg/executor/nfs/nfsrestorevolcreate.go
This reverts commit 2d70102900d4f463ec30bd0769e346a821785cfe, reversing changes made to 31782fe27ac10847869ccb2b9ee6d41d548a262a.
> Revert "Merge pull request #360 from portworx/PB-6687"

- pkg/controllers/dataexport/reconcile.go
- pkg/executor/common.go
- pkg/executor/kopia/kopiabackup.go
**What this PR does / why we need it**: Based on the azure Env type, it adds the storage domain in the repoCreate and repoConnect Command for azure cloud Provider
Closes # [PB-6677](https://purestorage.atlassian.net/browse/PB-6677)
**Unit Testing**
- vendored these stork changes to px-backup
- Passed the azure env type to backup location cr from px-backup and took a backup on that bl
- Enabled generic backup
- kopia tries to connect to the repo in case of AZURE_PUBLIC,  this validates the storage Domain
- In case of AZURE_CHINA, kopia tries to create the repo, validated storage domain from the repoCreateCommand
Repo Connect Command (Azure Public)
Repo Create Command (Azure China)
Repo Creation failed in case …
> Pb-6677: Add storage domain for azure cloud provider

- go.mod
- go.sum
- pkg/controllers/dataexport/reconcile.go
- pkg/executor/common.go
- pkg/executor/kopia/kopiabackup.go
- vendor/github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1/backuplocation.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go
- vendor/github.com/libopenstorage/stork/pkg/objectstore/azure/azure.go
- vendor/modules.txt
**What this PR does / why we need it**: It will push the changes from 1.2.12 branch to the master kdmp and will vendor stork master to the kdmp master
**Which issue(s) this PR fixes** (optional) 
Closes # https://purestorage.atlassian.net/browse/PB-6602
**Special notes for your reviewer**: na
> PB-6677: Push 1.2.12 kdmp changes to the master and vendor stork master

- go.mod
- go.sum
- vendor/github.com/libopenstorage/stork/drivers/volume/kdmp/kdmp.go
- vendor/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go
- vendor/github.com/libopenstorage/stork/drivers/volume/volume.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go
- vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go
- vendor/github.com/libopenstorage/stork/pkg/cache/cache.go
- vendor/github.com/libopenstorage/stork/pkg/resourcecollector/persistentvolume.go
- vendor/github.com/libopenstorage/stork/pkg/resourcecollector/resourcecollector.go
- vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter_csi.go
- vendor/modules.txt
**What this PR does / why we need it**: It vendors release-24.2.1 stork to kdmp 1.2.12
Closes #
**Special notes for your reviewer**:na
> PB-6862-vendor-stork: vendor release-24.2.1 stork to kdmp 1.2.12

- pkg/controllers/dataexport/reconcile.go
- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/options.go
- pkg/drivers/utils/utils.go
**What this PR does / why we need it**: This PR brings changes of psa and azure chine changes to kdmp via vending from stork to kdmp
Closes # pb-6681
Unit tested backup and restore with 1.2.13 executor image with corresponding stork PR
Restore of the above non-psi and psi backups are as below
> Enable kdmp & NFS  jobs to run in restricted PSA mode

- .travis.yml
- Dockerfile.unittest
- Makefile
Upgrading golang package 1.21.6 -> 1.21.11 to fix critical cve in nfsexecutor
Not fixing the kopia executor vulnerability as we need to update the kopia binary to 0.17.0 and it requires lot of changes and testing to make sure nothing is breaking.
Closes #
> PB-7300: upgrading packages to fix critical cve

- pkg/executor/nfs/nfsrestoreresources.go
**What type of PR is this?**
> Uncomment only one and also add the corresponding label in the PR:
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
>integration-test
**What this PR does / why we need it**: When taking Cloud Based CSI Backup such azure, gce, aws the csi based backup in case of replcace in default restore was going in pending state upon find the root cause the removeCSIVolumeBeforeApply was replacing the csi based pvc to default way. 
**Does this PR change a user-facing CRD or CLI?**:
**Is a release note needed?**:
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**:
ApplicationBackup
```
apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackup …
```
> PB-7158, PB-7159: Fix Handling of Cloud Based CSI Backups - NFS Location

- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/utils/utils.go
- When we use GCP based file store as NFS backup location, the job pod using that doesn't have write permission for group user, this causes the non-root user permission denied error during backup and restore.
- This is GKE specific behaviour hence a check added to force all job pod to run as a root user eradicating the permission denied error.
**What this PR does / why we need it**: This PR fixes the GKE resource backup and restore path wherein if NFS backup location is used then it will not use non-root user in any case. Hence no security context will be added.
Closes # pb-7504
Tested with kdmp volume + resource and then resource only 
restore of the same
> pb-7504: make NFS job pod to use root for resource backup

- pkg/controllers/dataexport/reconcile.go
- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/utils/utils.go
…
This PR pauses the cleanup that happens after the job is completed for the specified time in the PAUSE_RESOURCE_CLEANUP key.This is helpful incase of debugging to persist the resources for time mentioned 
Closes #PB-7645
Tested scenarios with value and without the key in the config map,working as expected:
- Without the key,cleanup is happening soon after it goes to completed state
- After adding key in configmap:
After the review comments:
> PB-7645: Add pause to cleanup of resources if env is set in kdmp-config configmap

- pkg/controllers/dataexport/reconcile.go
- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/drivers.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/utils/utils.go
> Revert "PB-7476: Adding node affinity to kopia backup and restore jobs"

- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/utils/utils.go
Add node affinity for kdmp live backup job pods with ROX or RWX access modes
**What this PR does / why we need it**:  To add node affinity for kdmp live backup job pods with ROX or RWX access modes
Closes # [PB-7859](https://purestorage.atlassian.net/browse/PB-7859)
**Node affinity set on node**
**RWO access mode, no node affinity set**
**RWO, RWX access mode, no node affinity set**
**RWX access mode, node affinity added**
**ROX access mode, node affinity added**
**RWX, ROX, RWO access modes, no node affinity set**
**RWX, ROX access modes, node affinity set**
**RWX, RWO access mode, node affinity not set**
[PB-7859]: https://purestorage.atlassian.net/browse/PB-7859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> PB-7859: Add node affinity for kdmp live backup job pods with ROX or RWX access modes

- pkg/controllers/dataexport/reconcile.go
```
pb-7868: Added nfs mountoptions for restore kdmp job with NFS
backuplocation.
- With out mountoptions the NFS backuplocation PVC mount was
failing as we were not passing the nfsvers option for nfsV4.
```
Closes # pb-7868
Testing:
validated  the restore from backup take on GKE filestore with nfsV4.
> pb-7868: Added nfs mountoptions for restore kdmp job with NFS backuplocation

- Makefile
- pkg/kopia/backup.go
- pkg/kopia/restore.go
…30 seconds (for real time logs)
**What this PR does / why we need it**: Currently the output of kopia backup/restore command is flushed in to the pod logs only after the cmd execution , so the user is not aware of the progress This PR Implements a new log writer which flushes the logs in every 30 seconds (for real time logs)
Closes # https://purestorage.atlassian.net/browse/PB-8293
Output for backup 
Attached additional testing details with logs in the ticket https://purestorage.atlassian.net/browse/PB-8293
> PB-8293 : Implement a new log writer which flushes the logs in every 30 seconds (for real time logs)

- pkg/controllers/dataexport/reconcile.go
- pkg/controllers/resourceexport/reconcile.go
- pkg/drivers/drivers.go
- pkg/drivers/kopiabackup/kopiabackup.go
- pkg/drivers/kopiarestore/kopiarestore.go
- pkg/drivers/nfsbackup/nfsbackup.go
- pkg/drivers/nfscsirestore/nfscsirestore.go
- pkg/drivers/nfsrestore/nfsrestore.go
- pkg/drivers/utils/utils.go
Sync the changes from 1.2.15 to kdmp master
Updating node label as per the best practices
commits cherry-picked from 1.2.15
- https://github.com/portworx/kdmp/commit/6e81b691073eaf617c0ec796eb878b44ac5123a0
- https://github.com/portworx/kdmp/commit/729f0037d61b8028f3db4ed5d5bc5b2b69fb03b9
- https://github.com/portworx/kdmp/commit/f50554dfb1677d1a6c5607a41a2722bb47774172
Closes #https://purestorage.atlassian.net/browse/PB-7476
**Special notes for your reviewer**:na
node affinity set after change of label case
> PB-7476-sync: Merging commits from 1.2.15 to master and updating node label as per the best practices
