portworx/kdmp

pkg/controllers/dataexport/reconcile.go, pkg/executor/common.go, pkg/executor/kopia/kopiabackup.go, pkg/kopia/backup.go, pkg/kopia/command.go, pkg/kopia/create.go
Adding support got GCE and Azure backend storage
PB-1865
Manual Test
Screenshot of repository and backup created on cloud providers
Azure repo
=> PB-1865: Supporting GKE and Azure for kopia repository

pkg/controllers/dataexport/reconcile.go, pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiabackup/kopiabackuplive.go, pkg/drivers/kopiarestore/kopiarestore.go, pkg/drivers/utils/common.go, pkg/executor/kopia/kopia.go, pkg/executor/kopia/kopiabackup.go
- Moved deleting VolumeBackup CR into cleanup() job
- Fixed issue in restore not updating VolumeBakcup CR for the failure scenario
PB-1882
=> PB-1882: Fixing issue with creating secret for multi ns

pkg/kopia/backup.go, pkg/kopia/connect.go, pkg/kopia/create.go, pkg/kopia/delete.go, pkg/kopia/global_policy.go, pkg/kopia/maintenancerun.go, pkg/kopia/maintenanceset.go, pkg/kopia/restore.go
- Add the stdout and stderr output to the error message. 
Closes #
=> PB-1920: Stringify all the errors returned by kopia

pkg/kopia/backup.go
Fetching backup size from backup response JSON content
PB-1934
Manual test
DataExprot CR once the backup is successful
```
[root@prashanth-iron-seer-0 kdmp]# k describe dataexport kopia-aws-mysql-1 -nrst
Name:         kopia-aws-mysql-1
Namespace:    rst
Labels:       <none>
Annotations:  <none>
API Version:  kdmp.portworx.com/v1alpha1
Kind:         DataExport
Metadata:
Creation Timestamp:  2021-09-29T13:17:33Z
Finalizers:
kdmp.portworx.com/finalizer-cleanup
Generation:  12
Managed Fields:
API Version:  kdmp.portworx.com/v1alpha1
Fields Type:  FieldsV1
fieldsV1:
f:metadata:
f:annotations:
.:
f:kubectl.kubernetes.io/last-applied-configuration:
f:spec:
.:
f:destination: …
```
=> PB-1934: Fetching backup size from backup response JSON content

pkg/drivers/drivers.go, pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiadelete/kopiadelete.go, pkg/drivers/kopiamaintenance/kopiamaintenance.go, pkg/drivers/kopiarestore/kopiarestore.go, pkg/drivers/resticbackup/resticbackup.go, pkg/drivers/resticrestore/resticrestore.go, pkg/drivers/utils/utils.go
PB-1856 Read the values from kdmp-config configmap instead of env
Closes # PB-1856
=> PB-1856 Read the values from kdmp-config configmap instead of env

pkg/kopia/restore.go
Adding support for fetching restore size
PB-1949
Manual test
=> PB-1949: Adding support to fetch restore size

pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiabackup/kopiabackuplive.go, pkg/drivers/kopiadelete/kopiadelete.go, pkg/drivers/kopiamaintenance/kopiamaintenance.go, pkg/drivers/kopiarestore/kopiarestore.go, pkg/drivers/options.go, pkg/drivers/utils/common.go
Supporting custom tls certificates for backup delete and maintenance jobs
PB-1945
=> PB-1945: Adding custom certificate support for delete and maintenance jobs

pkg/controllers/dataexport/reconcile.go, pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiabackup/kopiabackuplive.go, pkg/drivers/options.go
signed-off: Diptiranjan
Closes # PB-1999
**Test**:
1. Successful incremental generic backups for csi volumes with snapshotting.
2. Restoring backups.
=> [PB-1999]: For csi generic backup, kopia repo need to use the original source pvc instead of the staging pvc.

pkg/controllers/dataexport/reconcile.go
If PVC is already mounted to the job pod, and if the call again happens, need to ignore the error.
All restore with "restore-8-* " have been taken with this fix.
=> [STOR-551]: If pvc is already mounted to the job pod, ignore error in checkPVC.

go.mod, go.sum, pkg/apis/kdmp/v1alpha1/dataexport.go, pkg/controllers/dataexport/reconcile.go, vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter.go, vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter_csi.go, vendor/modules.txt
If the local snapshot is available for a volume, try to do the restore from that.
if it is not available or restore fails, move to generic restore.
Closes # OC-513
=> Support for restore using local snapshots in generic backup.

go.mod, go.sum, pkg/apis/kdmp/v1alpha1/dataexport.go, pkg/controllers/dataexport/reconcile.go, vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter.go, vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter_csi.go, vendor/modules.txt
stor-545: updated the missing step to update the volumeSnapshot in updateStatus
Closes # stor:545
=> Revert "Support for restore using local snapshots in generic backup."

go.mod, go.sum, pkg/apis/kdmp/v1alpha1/dataexport.go, pkg/controllers/dataexport/reconcile.go, vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter.go, vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter_csi.go, vendor/modules.txt
If the local snapshot is available for a volume, try to do the restore from that.
if it is not available or restore fails, move to generic restore.
Closes # 
OC-513
=> Support for restore using local snapshots in generic backup

pkg/kopia/backup.go
Removing kopia cmd error from passing to UI
PB-2019
=> PB-2019: Removing kopia cmd error from passing to UI

pkg/controllers/dataexport/reconcile.go, pkg/drivers/utils/common.go, pkg/drivers/utils/utils.go, pkg/executor/common.go, pkg/executor/kopia/kopiabackup.go
Fixing regression as follows - Don't count job pod count in case of job success
PB-2042
=> PB-2042: Fixing regression as follows - Don't count job pod count in case of job success

pkg/controllers/dataexport/reconcile.go
Reducing the timeout for volume bound check 
Closes # PB-2075
=> PB-2075: Making steps as 14 so that timeout happens in 20-30 mins range.

pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiabackup/kopiabackuplive.go, pkg/drivers/kopiadelete/kopiadelete.go, pkg/drivers/kopiamaintenance/kopiamaintenance.go, pkg/drivers/kopiarestore/kopiarestore.go, pkg/version/version.go
Change image pull policy to PullIfNotPresent
Closes #
=> Change image pull policy to PullIfNotPresent

pkg/controllers/dataexport/reconcile.go
pb-2113: Fixed the invalid access to the storage class variable if it is not present in the PV spec.
Closes # PR-2113
Tested on the QA setup. Now it is not crashing.
=> pb-2113: Fixed the invalid access to the storage class variable if it is not present in the PV spec.

pkg/controllers/dataexport/reconcile.go
```
pb-2113: cleanup in error handling in waitForPVCBound and checkPVCIgnoringJobMounts functions.
```
Closes #pb-2113
**Testing:**
**With out Fix:**
**With Fix:**
=> pb-2113: cleanup in error handling in waitForPVCBound and checkPVCIgnoringJobMounts functions.

pkg/controllers/dataexport/reconcile.go
pb-2156: Failing the backup, if the local snapshot backup or restore fails.
Closes # pb-2156
Testing:
Tested on OCP cluster by commenting out the default to KDMP in the case of the OCP provisioner.
After timeout, backup will be marked with the failure instead of retry and hanging.
=> pb-2156: Failing the backup, if the local snapshot backup or restore fails

pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiabackup/kopiabackuplive.go
```
pb-2162: Added fixes for backup/restore on ocp environment.
- Added privileged scc for job role
```
Closes # pb-2162
Tested the fix on Kshithij's setup.
=> pb-2162: Added fixes for backup/restore on ocp environment.

Makefile
**What this PR does / why we need it**: 
This fixes the occurrence of failure in staticcheck phase by locking it to a specified version 
Closes #
=> Update Makefile to fix staticcheck issue

pkg/drivers/kopiadelete/kopiadelete.go, pkg/drivers/kopiamaintenance/kopiamaintenance.go, pkg/drivers/options.go, pkg/version/version.go
Adding nodeAffinity for kopia maintenance and delete jobs
baas-55`
=> baas-551: Adding nodeAffinity for kopia maintenance jobs

pkg/controllers/dataexport/reconcile.go, pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiabackup/kopiabackuplive.go, pkg/drivers/kopiarestore/kopiarestore.go, pkg/drivers/utils/utils.go
```
pb-2377: Creating image secret in job pod namespace.
- Added prefix for secrets like image, cred and cret for
different secret type.
```
Closes # pb-2377
Testing:
1) Made docker repo for stork image to be private and create a image secret for the stork deployment in my setup.
```
root@ip-10-13-108-165:~# kubectl describe deploy strok -n kube-system | grep regcred
Error from server (NotFound): deployments.apps "strok" not found
root@ip-10-13-108-165:~# kubectl describe secret regcred  -n kube-system
Name:         regcred
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
Type:  kubernetes.io/dockerconfigjson
Data
====
.dockerconfigjson:  103 bytes …
```
=> pb-2377: Creating image secret in job pod namespace.

pkg/executor/nfs/nfs.go, pkg/executor/nfs/nfsrestoreresources.go
restoring resources executor
Closes # PB-3058
=> PB-3058: Command executor for restoring resources.

pkg/drivers/kopiadelete/kopiadelete.go
=> PB-3054 - Added changes required for NFS snapshot delete job

pkg/apis/kdmp/v1alpha1/resourceexport.go, pkg/controllers/resourceexport/reconcile.go, pkg/controllers/resourceexport/resourceexport.go, pkg/drivers/options.go
Fixing issue in reconciler and job framework, missed with previous commit
PB-3093
=> PB 3093:Fixing issue in reconciler and job framework, missed with previous commit

pkg/drivers/drivers.go, pkg/drivers/driversinstance/driversinstance.go, pkg/drivers/nfsdelete/nfsdelete.go, pkg/drivers/utils/utils.go, pkg/executor/nfs/nfs.go, pkg/executor/nfs/nfsdeleteresources.go, pkg/jobratelimit/jobratelimit.go
**What this PR does / why we need it**: NFS executor changes for NFS resource delete via job
Closes #
=> PB-2970 - NFS executor changes for NFS resource delete

pkg/controllers/resourceexport/reconcile.go
```
pb-3112: Added restore changes in resourceexport reconciler code.
```
Closes # pb-3112
Will test it Dipti's restore changes. Currently it is untested.
=>  pb-3112: Added restore changes in resourceexport reconciler code.

pkg/drivers/nfsrestore/nfsrestore.go, pkg/executor/common.go, pkg/executor/nfs/nfsbkpresources.go, pkg/executor/nfs/nfsdeleteresources.go, pkg/executor/nfs/nfsrestoreresources.go
=> PB-3060: Updating the resource status in resource backup CR.

pkg/controllers/resourceexport/reconcile.go, pkg/controllers/resourceexport/resourceexport.go
**What this PR does / why we need it**: Removes the flooding logs which appears in stork pod.
Closes # pb-3133
=> pb-3133: Removing logs that is flooding the stork pod.

pkg/executor/nfs/nfsbkpresources.go
Added logic to encrypt resource files while storing them to NFS based backuplocation.
**What this PR does / why we need it**: this enables the encryption if NFS backuplocation had a NFS key set on it
Closes #pb-3143
UNIT TEST :
to enable the encryption via pxbackupctl use the command as below 
`
./pxbackupctl/linux/pxbackupctl create backuplocation -n nfs-bl-encrypted -p nfs --validate-cloud-credential false --encryption-key="key01" --endpoint localhost:10002 --authtoken=$authtoken --nfs-server-addr "10.13.184.233" --path "/mnt/nfs-share2"
Backup location nfs-bl-encrypted created successfully
`
The nfs-share at server side screen shot is as below. Only the …
=> pb-3143: Enable encryption for NFS resource backup

pkg/executor/nfs/nfsrestoreresources.go
Signed-off-by: Diptiranjan
Tested with single and multi ns restores.
=> PB-3144: Creating namespaces in the restore job if required for nfs location.

pkg/drivers/nfsbackup/nfsbackup.go, pkg/drivers/nfsdelete/nfsdelete.go, pkg/drivers/nfsrestore/nfsrestore.go, pkg/executor/nfs/nfsrestoreresources.go
```
pb-3171: Added Imagepullsecret in the job pod spec for nfs related jobs.
```
Closes # pb-3171
=> pb-3171: Added Imagepullsecret in the job pod spec for nfs related jobs.

pkg/executor/nfs/nfsrestoreresources.go
```
pb-3211: Fixed issue in updating the resource status in resource backup CR
```
Closes # pb-3211
Tested with resource and now resource count comes fine.
Dependent pr: https://github.com/libopenstorage/stork/pull/1202 ( from stork)
=> pb-3211: Fixed issue in updating the resource status in resource backup CR.

pkg/apis/kdmp/v1alpha1/resourceexport.go, pkg/drivers/utils/utils.go
**What this PR does / why we need it**: Fixed review comment and adds a field in CR to know wherefrom the CR creation is triggered such as px-backup or stork
Closes #
=> Added TriggeredFrom spec field in ResourceExport CR

pkg/controllers/dataexport/reconcile.go, pkg/controllers/resourceexport/reconcile.go, pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiabackup/kopiabackuplive.go, pkg/drivers/kopiadelete/kopiadelete.go, pkg/drivers/kopiamaintenance/kopiamaintenance.go, pkg/drivers/kopiarestore/kopiarestore.go, pkg/drivers/nfsbackup/nfsbackup.go, pkg/drivers/nfsdelete/nfsdelete.go, pkg/drivers/nfsrestore/nfsrestore.go, pkg/drivers/utils/common.go, pkg/drivers/utils/utils.go
=> Added a common function to return pv & pvc name

pkg/executor/nfs/nfsbkpresources.go, pkg/executor/nfs/nfsdeleteresources.go
Closes # [PB-3240](https://portworx.atlassian.net/browse/PB-3240)
=> PB-3240 - Fix nfs delete resource to delete the correct directory

pkg/drivers/kopiabackup/kopiabackup.go, pkg/drivers/kopiabackup/kopiabackuplive.go, pkg/drivers/kopiadelete/kopiadelete.go, pkg/drivers/kopiamaintenance/kopiamaintenance.go, pkg/drivers/kopiarestore/kopiarestore.go, pkg/drivers/nfsbackup/nfsbackup.go, pkg/drivers/nfsdelete/nfsdelete.go, pkg/drivers/nfsrestore/nfsrestore.go, pkg/drivers/utils/utils.go
**What this PR does / why we need it**: Added changes to support toleration on all the kopia and NFS jobs. Additionally, node affinities are added to delete, maintenance jobs
Closes #[PB-3193](https://portworx.atlassian.net/browse/PB-3193)
=> [PB-3193] Added support for toleration and node affinity in jobs

pkg/executor/nfs/nfsrestorevolcreate.go
```
pb-3276: Updating the unstructed PVC object to point to correct namespace based on the ns mapping.
```
Closes # pb-3276
Verified following two cases:
Case1:
- Took single namespace backup and deleted the source SC
- Triggered restore to different namespace and different SC.
Case2:
- Took multi namespace backup of same app ( to have same PVC name)
- Deleted the source SC.
- Maunally created the destination namespaces ( as fix for creation of multi namepspace is pending)
- Trigged restore to different namespace and different SC.
=> pb-3276: Updating the unstructed PVC object to point to correct namespace based on the ns mapping.

pkg/executor/common.go, pkg/executor/nfs/nfsbkpresources.go, pkg/executor/nfs/nfsrestoreresources.go, pkg/executor/nfs/nfsrestorevolcreate.go
=> PB-3296: UpdateResourceBackupStatus should not update the resources from status as it is reverting the old resources update.

pkg/executor/nfs/nfsrestorevolcreate.go
Added appropriate status when converting volbkp status to RE volinfo
pb-3306
=> pb-3306: Added appropriate status when converting volbkp status to RE volinfo

pkg/executor/nfs/nfsbkpresources.go
```
PB-3430: support for uploading storageclasses.json to nfs backuplocation
- For native csi driver, added support for uploading the
storageclasses.json to nfs backuplocation target
- For nfs backuplocation, the storageclasses.json will be
uploaded in the resource stage along with other resource json files,
as part of nfs executer job.
```
Closes # pb-3430
Testing:
- Added some hack to validate the fix:
- Remove the check to default the csi to kdmp, in the case of nfs backuplocation.
- Also commented out the code to upload the snapshot.json. This will be supported in the next PR.
- Verified the content of the storageclasses.json between s3 bucket and nfs backuplocation …
=> PB-3430: support for uploading storageclasses.json to nfs backuplocation

pkg/controllers/dataexport/reconcile.go
Closes # PB-3500
**Test**:
Test results have been updated in PB-3500.
=> PB-3500: Retaining the local csi snapshot for all kdmp csi backups.

.travis.yml, Dockerfile, Dockerfile.resticexecutor, Dockerfile.unittest
1. Build to use xenial build environment on the Travis CI platform
2. Ubuntu Base image set to latest
Closes #
=> Use focal build environment on Travis CI

Makefile
```
pb-3452: Makefile changes for docker build
```
Closes # pb-3452
=> pb-3452: Makefile changes for docker build

go.mod, go.sum, pkg/controllers/dataexport/reconcile.go, pkg/executor/nfs/nfsbkpresources.go, vendor/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go, vendor/modules.txt
Uploading csi snapshot info for volumes which have taken csi snapshot path for generic backup.
Closes # PB-3453
=> PB-3453: Uploading csi snapshot info for generic backups.

Dockerfile.kopia
**What this PR does / why we need it**: Contains changes to upgrade kopia binary version to fix critical CVEs
Closes # [PB-3649](https://portworx.atlassian.net/browse/PB-3649)
[PB-3649]: https://portworx.atlassian.net/browse/PB-3649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PB-3649 - Added fix to mitigate critical CVEs

pkg/apis/kdmp/v1alpha1/resourcebackup.go, pkg/apis/kdmp/v1alpha1/resourceexport.go, pkg/controllers/dataexport/reconcile.go, pkg/controllers/resourceexport/reconcile.go, pkg/executor/common.go, pkg/executor/nfs/nfsrestoreresources.go, pkg/executor/nfs/nfsrestorevolcreate.go
**What this PR does / why we need it**: This adds support for LargeResource support for NFS backup location
Closes # pb-3842
Unit test : 
show status of large resource restore 
largeResource falg enabled in case of restore
=> Pb 3842 large resource support in nfs

pkg/executor/nfs/nfsrestorevolcreate.go
```
pb-3904 avoid downloading of storageclass.json for non csi restore
```
Closes #pb-3904
Tested non csi restore on QA setup.
=> pb-3904 avoid downloading of storageclass.json for non csi restore

pkg/executor/nfs/nfsbkpresources.go
```
pb-3909: Need to remove the namespace that does not contain resource to
backup
- In theog nfs resource backup, we do all the filtering for the
include resource and resourcetype in stork itself.
- To the nfs executor, we pass the final list of resource in
applicationbackup CR and work on it alone.
- In that we need to pass only the namespace that containe the
final list of resource to GetResource.
```
Closes # pb-3909
Testing:
Validated follow cases:
1) Two ns backup with resoucetype cm. One namespace had cm and sa. Other namespace has all type of resource expect cm. It took backup of first namespace for cm alone.
2) Verified that custom selection of resource in the …
=> pb-3909: Need to remove the namespace that does not contain resource to backup

pkg/controllers/dataexport/reconcile.go
```
pb-3928: Fixed issue in cleaning up the vs and vsc in the case of kdmp
localsnapshot restore.
- Now getting the restore PVC spec to get the volumesnapshot
name and calling snapshotDriver.DeleteSnapshot api to delete vs and vsc.
```
Closes # pb-3928
**Testing:**
Tested kdmp localsnapshot and verified that vs and vsc are getting deleted.
=> pb-3928: Fixed issue in cleaning up the vs and vsc in the case of kdmp localsnapshot restore.

pkg/executor/common.go
**What this PR does / why we need it**:  Added changes for rancher projectmapping in namespaces in case of NFS BL
Closes # [PB-3919](https://portworx.atlassian.net/browse/PB-3919)
**Backup taken on the namespace**
**Restoring to a new namespace to a different project**
**Restoring same namespace to a different project**
**Restoring same namespace after removing project association  to a different project**
[PB-3919]: https://portworx.atlassian.net/browse/PB-3919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added changes for rancher projectmapping in namespaces in case of NFS BL

pkg/executor/kopia/kopiadelete.go
**What this PR does / why we need it**:   Added fix to check for the existence of kopia repository file in kdmp delete, safely exit when repo file is not found.
Closes # [PB-3949](https://portworx.atlassian.net/browse/PB-3949)
[PB-3949]: https://portworx.atlassian.net/browse/PB-3949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PB-3949: Added fix to check for the existence of kopia repository file in kdmp delete

pkg/controllers/dataexport/reconcile.go
```
pb-4023: Added code to clean up the VS and VSC in the case of KDMP & localsnapshot.
- Need to delete the volumesnapshot and volumesnapshotcontent for KDMP + localsnapshot backup variant in the following cases.
- When the S3 and NFS backuplocation localsnapshot fails with KDMP + localsnapshot.
It is possible that CSI snapshot might fails with timeout error, if the snapshot takes time or snapshot is not support by CSI controller.
- When the snapshot succeeds with S3 backuplocation/KDMP + localsnapshot, we need to delete the VS and VSC, in the volume stage itself.
- When the snapshot succeeds with NFS backuplocation/KDMP + localsnapshot, we will NOT delete the VS and VSC in the volume stage.
It will be deleted in the resource stage after the VS and …
```
=> pb-4023: Added code to clean up the VS and VSC in the case of KDMP & localsnapshot.

pkg/executor/common.go
```
pb-4322: Fix issue in updating the large kdmp job LastKnownError to
volumebackup CR status.
- Some time, the kdmp job LastKnownError are very large and
exceeds th etcd large request size of 1.5M.
- So avoid the update of kdmp job LastKnownError in volumebackup
CR status and dump them in job pod log
```
Closes # pb-4322
=> pb-4322: Fix issue in updating the large kdmp job LastKnownError to volumebackup CR status.

Dockerfile.kopia
**What this PR does / why we need it**: Upgraded kopia version to 14.1 for fixing critical CVEs
Closes #  https://portworx.atlassian.net/browse/PB-4472
=> PB-4472 - Upgraded kopia version to 14.1 for fixing critical CVEs

pkg/controllers/dataexport/reconcile.go
…led in bl
**What this PR does / why we need it**: Added changes to avoid creationg of job cred secret when ssl is disabled in backup location
Closes #
=> Added changes to avoid creationg of job cred secret when ssl is disabled

pkg/controllers/dataexport/reconcile.go
```
pb-4872: reverted the setting of default compression type
```
Closes # pb--4872
Reverted the changes as it will need more testing. Will pick it up in next release.
=> pb-4872: reverted the setting of default compression type

pkg/controllers/dataexport/reconcile.go
```
pb-5019: Added logic to fetch the default encryption type for FBDA, if
it is not set in the kdmp-config cm.
- frst case, if the exclude file list key is empty in the
kdmp-config cm, we will try to set the default exclude file list for
FBDA, if the storage class is FBDA.
- second case, if the exclude file list key is not empty in the
kdmp-cpnfig cm, if it did not had rule for FBDA storage class, we will
try to set the degault execlude file list for the FBD, if the storage
class is FBDA.
```
Closes # pb-5019
Testing:
Tested below two cases:
1) Did not had any exlcude file list key parameter in the kdmp-config cm and took backup of FBDA vdbench namespace and restored …
=> pb-5019: Added logic to fetch the default encryption type for FBDA, if

Makefile
**What this PR does / why we need it**: It fixes the master build failure
Closes [PB-5272](https://portworx.atlassian.net/browse/PB-5272)
[PB-5272]: https://portworx.atlassian.net/browse/PB-5272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix for the master build failure

pkg/executor/kopia/kopiabackup.go
**What this PR does / why we need it**: It captures the error returned by api calls while trying to check if repo exists, which can help debugging incase the check times out
Closes #[PB-5272](https://portworx.atlassian.net/browse/PB-5272)
[PB-5272]: https://portworx.atlassian.net/browse/PB-5272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> capturing actual error msg while trying to check if repo exists

pkg/version/version.go
=> version of the master branch changed from 1.2.11 to master-latest

pkg/controllers/dataexport/reconcile.go
Closes #
Vendor Fix for PR -  https://github.com/libopenstorage/stork/pull/1671  it was mistakenly updated the vendor files
=> PB-6319 : Vendor fix Stork x KDMP

pkg/controllers/dataexport/reconcile.go
- Backup(kdmp+localsnapshot) hangs in InProgress state while creating backup through api/pxbackupctl using "Use-default-volumesnapshotclass" in csianpashotclassmap. 
- We should error out to user incase backup fails for any reason
Closes #
PB-6377
=> PB-6377-kdmplocalsnapshot backup hangs in InProgress state

go.mod, go.sum, vendor/github.com/libopenstorage/stork/drivers/volume/csi/csi.go, vendor/github.com/libopenstorage/stork/drivers/volume/kdmp/kdmp.go, vendor/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go, vendor/github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1/applicationbackup.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackupschedule.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go, vendor/github.com/libopenstorage/stork/pkg/utils/utils.go, vendor/modules.txt
This PR is part of the feature to support NFS backup and restore. But this PR is only for the vendor related changes.
Closes #
=> PB-6205: Vendor changes - Vendored from stork partial_success to kdmp

go.mod, go.sum, pkg/controllers/dataexport/reconcile.go, vendor/github.com/libopenstorage/stork/drivers/volume/kdmp/kdmp.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go, vendor/github.com/libopenstorage/stork/pkg/resourcecollector/resourcecollector.go, vendor/github.com/libopenstorage/stork/pkg/rule/rule.go, vendor/github.com/libopenstorage/stork/pkg/utils/utils.go, vendor/github.com/portworx/sched-ops/k8s/common/pod.go, vendor/github.com/portworx/sched-ops/k8s/core/pods.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go, vendor/modules.txt
Release branch PR for PB-4394
Closes #
PB-4393
=> fix: PB-4394 vendor changes to have fix work for NFS BL

go.mod, go.sum, vendor/github.com/libopenstorage/stork/pkg/snapshotter/snapshotter_csi.go, vendor/modules.txt
Vendor latest 24.1.0 stork in to kdmp for PB-6814
Closes #
PB-6814
=> Vendor latest stork for PB-6814

go.mod, go.sum, pkg/executor/nfs/nfsrestoreresources.go, vendor/github.com/libopenstorage/stork/drivers/volume/volume.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go, vendor/github.com/libopenstorage/stork/pkg/resourcecollector/persistentvolume.go, vendor/modules.txt
=> PB-6903: Fix Cloud Native Restore Path

pkg/executor/nfs/nfsrestorevolcreate.go
=> PB-6687 :: Skip Portworx Volume in Case NFS Restore

pkg/executor/nfs/nfsbkpresources.go, pkg/executor/nfs/nfsrestorevolcreate.go, vendor/github.com/libopenstorage/stork/drivers/volume/csi/csi.go, vendor/github.com/libopenstorage/stork/drivers/volume/kdmp/kdmp.go, vendor/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go, vendor/github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1/applicationbackup.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackupschedule.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go, vendor/github.com/libopenstorage/stork/pkg/utils/utils.go
Support for partial success backup
EPIC pb-4585
All test result captured in test rail
https://portworx.testrail.net/index.php?/suites/view/1&group_by=cases:section_id&group_id=9195&group_order=asc&display_deleted_cases=0
=> Support for Partial success backups

go.mod, go.sum, vendor/github.com/libopenstorage/stork/drivers/volume/kdmp/kdmp.go, vendor/github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1/backuplocation.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationrestore.go, vendor/github.com/libopenstorage/stork/pkg/objectstore/azure/azure.go, vendor/github.com/libopenstorage/stork/pkg/snapshot/controllers/snapshotschedule.go, vendor/github.com/libopenstorage/stork/pkg/utils/utils.go, vendor/modules.txt
This brings PSA changes of stork to kdmp
Closes #
=> vendor stork pxb-2.7.2 to kdmp 1.2.13

.travis.yml, pkg/version/version.go
=> Altered travis.yaml & version.go to reflect master branch details

go.mod, go.sum, vendor/github.com/libopenstorage/stork/pkg/applicationmanager/controllers/applicationbackup.go, vendor/github.com/libopenstorage/stork/pkg/snapshot/controllers/snapshotschedule.go, vendor/github.com/libopenstorage/stork/pkg/utils/utils.go, vendor/modules.txt
Closes # pb-7392
check the pb-ticket pb-7392
=> pb-7392: vendored stork master to kdmp master

Makefile
Closes #
Build passing in local
=> fix errorcheck install in makefile
